-- IDEMPIERE-4845
-- 23.06.2021, 10:26:41 MESZ
INSERT INTO AD_Message (MsgType,MsgText,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,AD_Message_ID,Value,EntityType,AD_Message_UU) VALUES ('E','No product with specified attribute set instance is stored: {0}',0,0,'Y',TO_TIMESTAMP('2021-06-23 10:26:35','YYYY-MM-DD HH24:MI:SS'),100,TO_TIMESTAMP('2021-06-23 10:26:35','YYYY-MM-DD HH24:MI:SS'),100,200712,'NoProductWithAsi','D','98925dc0-f2fb-4801-be0e-553904c92377')
;
-- AMEND-IDEMPIERE-4845
-- 28.06.2021, 08:43:38 MESZ
INSERT INTO AD_Column (AD_Column_ID,Version,Name,Help,AD_Table_ID,ColumnName,DefaultValue,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Reference_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,SeqNoSelection,IsToolbarButton,IsSecure,FKConstraintType,IsHtml) VALUES (214520,0,'Auto Generated','Record is Auto Generated by System.',765,'IsAutoGenerated','N',1,'N','N','N','N','N',0,'N',20,0,0,'Y',TO_TIMESTAMP('2021-06-28 08:43:33','YYYY-MM-DD HH24:MI:SS'),100,TO_TIMESTAMP('2021-06-28 08:43:33','YYYY-MM-DD HH24:MI:SS'),100,202701,'N','N','D','N','N','N','Y','442e9fd0-9587-4ea3-9f77-2126731561bf','Y',0,'N','N','N','N')
;

-- 28.06.2021, 08:43:45 MESZ
ALTER TABLE M_ProductionLineMA ADD COLUMN IsAutoGenerated CHAR(1) DEFAULT 'N' CHECK (IsAutoGenerated IN ('Y','N'))
;

SELECT register_migration_script('202106291050_IDEMPIERE-4845.sql') FROM dual