<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pde" nsURI="http://www.eclipse.org/oomph/setup/pde/1.0" nsPrefix="pde">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="schemaLocation" value="http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/setups/models/PDE.ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/oomph/setup/Enablement">
    <details key="variableName" value="setup.pde.p2"/>
    <details key="repository" value="${oomph.update.url}"/>
    <details key="installableUnits" value="org.eclipse.oomph.setup.pde.feature.group"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/oomph/base/LabelProvider">
    <details key="imageBaseURI" value="http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/plugins/org.eclipse.oomph.setup.pde.edit/icons/full/obj16"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TargetPlatformTask" eSuperTypes="http://www.eclipse.org/oomph/setup/1.0#//SetupTask">
    <eAnnotations source="http://www.eclipse.org/oomph/setup/ValidTriggers">
      <details key="triggers" value="STARTUP MANUAL"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractAPIBaselineTask" abstract="true"
      eSuperTypes="http://www.eclipse.org/oomph/setup/1.0#//SetupTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APIBaselineTask" eSuperTypes="#//AbstractAPIBaselineTask">
    <eAnnotations source="http://www.eclipse.org/oomph/setup/ValidTriggers">
      <details key="triggers" value="STARTUP MANUAL"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="">
      <eAnnotations source="http://www.eclipse.org/oomph/setup/Variable">
        <eAnnotations source="Choice">
          <details key="value" value="${api.baselines.root/}${@id.name|lower}-${@id.version}"/>
          <details key="label" value="Located in a folder named '&lt;name>-&lt;version>' within the root API baselines folder"/>
        </eAnnotations>
        <eAnnotations source="Choice">
          <details key="value" value="${installation.location/baselines/}${@id.name|lower}-${@id.version}"/>
          <details key="label" value="Located in a folder named 'baselines/&lt;name>-&lt;version>' within the installation folder"/>
        </eAnnotations>
        <eAnnotations source="Choice">
          <details key="value" value="${workspace.location/.baselines/}${@id.name|lower}-${@id.version}"/>
          <details key="label" value="Located in a folder named '.baselines/&lt;name>-&lt;version>' within the workspace folder"/>
        </eAnnotations>
        <eAnnotations source="Choice">
          <details key="value" value="${@id.location}"/>
          <details key="label" value="Located in the specified absolute folder location"/>
        </eAnnotations>
        <details key="type" value="STRING"/>
        <details key="label" value="API baseline location rule"/>
        <details key="description" value="The rule for the absolute folder location where the API baseline is located"/>
        <details key="explicitType" value="FOLDER"/>
        <details key="explicitLabel" value="${@id.name}-${@id.version} API baseline location"/>
        <details key="explicitDescription" value="The absolute folder location where the ${@id.name}-${@id.version} API baseline is located"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/oomph/setup/RuleVariable">
        <details key="name" value="api.baselines.root"/>
        <details key="type" value="FOLDER"/>
        <details key="label" value="Root API baselines folder"/>
        <details key="description" value="The root API baselines folder where all the API baselines are located"/>
        <details key="storageURI" value="scope://"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remoteURI" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/oomph/setup/RemoteResource"/>
      <eAnnotations source="http://www.eclipse.org/oomph/setup/Redirect"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APIBaselineFromTargetTask" eSuperTypes="#//AbstractAPIBaselineTask">
    <eAnnotations source="http://www.eclipse.org/oomph/setup/ValidTriggers">
      <details key="triggers" value="STARTUP MANUAL"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="">
      <eAnnotations source="http://www.eclipse.org/oomph/setup/Variable">
        <eAnnotations source="Choice">
          <details key="value" value="${api.baselines.root/}${@id.name|lower}-${@id.version}"/>
          <details key="label" value="Located in a folder named '&lt;name>-&lt;version>' within the root API baselines folder"/>
        </eAnnotations>
        <eAnnotations source="Choice">
          <details key="value" value="${installation.location/baselines/}${@id.name|lower}-${@id.version}"/>
          <details key="label" value="Located in a folder named 'baselines/&lt;name>-&lt;version>' within the installation folder"/>
        </eAnnotations>
        <eAnnotations source="Choice">
          <details key="value" value="${workspace.location/.baselines/}${@id.name|lower}-${@id.version}"/>
          <details key="label" value="Located in a folder named '.baselines/&lt;name>-&lt;version>' within the workspace folder"/>
        </eAnnotations>
        <eAnnotations source="Choice">
          <details key="value" value="${@id.location}"/>
          <details key="label" value="Located in the specified absolute folder location"/>
        </eAnnotations>
        <details key="type" value="STRING"/>
        <details key="label" value="API baseline location rule"/>
        <details key="description" value="The rule for the absolute folder location where the API baseline is located"/>
        <details key="explicitType" value="FOLDER"/>
        <details key="explicitLabel" value="${@id.name}-${@id.version} API baseline location"/>
        <details key="explicitDescription" value="The absolute folder location where the ${@id.name}-${@id.version} API baseline is located"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/oomph/setup/RuleVariable">
        <details key="name" value="api.baselines.root"/>
        <details key="type" value="FOLDER"/>
        <details key="label" value="Root API baselines folder"/>
        <details key="description" value="The root API baselines folder where all the API baselines are located"/>
        <details key="storageURI" value="scope://"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
