-- IDEMPIERE-5567 Support of UUID as Key (FHCA-4195)
SELECT register_migration_script('202307162331_IDEMPIERE-5567_EnableChangeLog.sql') FROM dual;

-- enable changelog in tables without ID PKey
UPDATE ad_table SET ischangelog='Y'
WHERE ischangelog='N' AND tablename IN (
'AD_Document_Action_Access',
'AD_FieldSuggestion',
'AD_Form_Access',
'AD_ImportTemplateAccess',
'AD_InfoWindow_Access',
'AD_LdapAccess',
'AD_Note',
'AD_PostIt',
'AD_Private_Access',
'AD_Process_Access',
'AD_Record_Access',
'AD_ReportView_Column',
'AD_Role_Included',
'AD_Role_OrgAccess',
'AD_Scheduler_Para',
'AD_Sequence_Audit',
'AD_Sequence_No',
'AD_Session',
'AD_Table_Access',
'AD_Task_Access',
'AD_UserMail',
'AD_User_OrgAccess',
'AD_User_Roles',
'AD_Window_Access',
'AD_Workflow_Access',
'A_FundingMode_Acct',
'A_RegistrationProduct',
'A_RegistrationValue',
'A_Valid_Asset_Combinations',
'C_BankAccount_Acct',
'C_BankAccount_Processor',
'C_BPartner_Product',
'C_BP_Customer_Acct',
'C_BP_Employee_Acct',
'C_BP_Vendor_Acct',
'C_BP_Withholding',
'C_CashBook_Acct',
'C_Charge_Acct',
'C_ChargeType_DocType',
'C_Currency_Acct',
'C_CyclePhase',
'C_InterOrg_Acct',
'C_Project_Acct',
'C_ProjectIssueMA',
'C_RevenueRecog_Service',
'C_Tax_Acct',
'C_Withholding_Acct',
'M_AttributeInstance',
'M_AttributeUse',
'M_InOutLineMA',
'M_InventoryLineMA',
'M_MovementLineMA',
'M_Product_Acct',
'M_Product_Category_Acct',
'M_ProductionLineMA',
'M_Product_PO',
'M_RelatedProduct',
'M_Replenish',
'M_Substitute',
'M_TransactionAllocation',
'M_Warehouse_Acct',
'PA_DashboardContent_Access',
'R_CategoryUpdates',
'R_ContactInterest',
'R_GroupUpdates',
'R_RequestTypeUpdates',
'R_RequestUpdates',
'WS_WebServiceTypeAccess'
)
;

