-- IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) - test data
SELECT register_migration_script('202306101728_IDEMPIERE-5567-TestPrintFormat.sql') FROM dual;

SET SQLBLANKLINES ON
SET DEFINE OFF

-- Jun 10, 2023, 5:28:56 PM CEST
INSERT INTO AD_PrintFormat (Updated,CreatedBy,IsTableBased,IsActive,IsStandardHeaderFooter,AD_PrintFont_ID,AD_Table_ID,IsForm,HeaderMargin,UpdatedBy,AD_PrintColor_ID,Created,Name,FooterMargin,AD_Client_ID,AD_PrintPaper_ID,AD_Org_ID,AD_PrintFormat_ID,IsDefault,AD_PrintFormat_UU,IsBreakPagePerRecord) VALUES (TO_TIMESTAMP('2023-06-10 17:28:56','YYYY-MM-DD HH24:MI:SS'),100,'Y','Y','Y',130,200384,'N',0,100,100,TO_TIMESTAMP('2023-06-10 17:28:56','YYYY-MM-DD HH24:MI:SS'),'TestUUDet Print Format',0,0,100,0,200016,'N','431e6b2e-3a28-4d0f-8fed-9aa94a922e28','Y')
;

-- Jun 10, 2023, 5:28:57 PM CEST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,PrintName,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,IsNextPage,IsFixedWidth,IsMaxCalc,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc,IsPrintBarcodeText,IsPrintInstanceAttributes) VALUES (0,'Active',TO_TIMESTAMP('2023-06-10 17:28:56','YYYY-MM-DD HH24:MI:SS'),'N',0,'Active',0,0,215801,'N','Y',100,0,200396,100,'N',0,TO_TIMESTAMP('2023-06-10 17:28:56','YYYY-MM-DD HH24:MI:SS'),200016,0,0,'Y','N',0,0,'L','N','N','N','X','F','C','N','N','N','N','N','N','N','N','N','N','N','N','N',1,0,'N','Y','N','N','f84e0f71-b380-42ce-9d6c-b16238708e98','N','Y','N')
;

-- Jun 10, 2023, 5:28:57 PM CEST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,PrintName,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,IsNextPage,IsFixedWidth,IsMaxCalc,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc,IsPrintBarcodeText,IsPrintInstanceAttributes) VALUES (0,'Organization',TO_TIMESTAMP('2023-06-10 17:28:57','YYYY-MM-DD HH24:MI:SS'),'N',0,'Organization',0,0,215796,'N','Y',100,0,200397,100,'N',0,TO_TIMESTAMP('2023-06-10 17:28:57','YYYY-MM-DD HH24:MI:SS'),200016,0,0,'Y','N',0,0,'L','N','N','N','X','F','C','N','N','N','N','N','N','N','N','N','N','N','N','N',1,0,'N','Y','N','N','14f52d41-e411-4be0-a2c3-885470f11173','N','Y','N')
;

-- Jun 10, 2023, 5:28:58 PM CEST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,PrintName,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,IsNextPage,IsFixedWidth,IsMaxCalc,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc,IsPrintBarcodeText,IsPrintInstanceAttributes) VALUES (0,'Tenant',TO_TIMESTAMP('2023-06-10 17:28:57','YYYY-MM-DD HH24:MI:SS'),'N',0,'Tenant',0,0,215795,'N','Y',100,0,200398,100,'N',0,TO_TIMESTAMP('2023-06-10 17:28:57','YYYY-MM-DD HH24:MI:SS'),200016,0,0,'Y','N',0,0,'L','N','N','N','X','F','C','N','N','N','N','N','N','N','N','N','N','N','N','N',1,0,'N','Y','N','N','bb9a523d-be00-4436-8a4b-afec620505c5','N','Y','N')
;

-- Jun 10, 2023, 5:28:58 PM CEST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,PrintName,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,IsNextPage,IsFixedWidth,IsMaxCalc,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc,IsPrintBarcodeText,IsPrintInstanceAttributes) VALUES (10,'Test UU',TO_TIMESTAMP('2023-06-10 17:28:58','YYYY-MM-DD HH24:MI:SS'),'N',0,'Test UU',0,0,215805,'N','Y',100,0,200399,100,'N',0,TO_TIMESTAMP('2023-06-10 17:28:58','YYYY-MM-DD HH24:MI:SS'),200016,0,0,'Y','N',0,0,'L','N','N','N','X','F','C','N','N','N','N','N','N','N','N','N','N','N','N','N',1,0,'N','Y','N','N','64332931-f7a2-4cad-b786-89503d0b0776','N','Y','N')
;

-- Jun 10, 2023, 5:28:58 PM CEST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,PrintName,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,IsNextPage,IsFixedWidth,IsMaxCalc,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc,IsPrintBarcodeText,IsPrintInstanceAttributes) VALUES (10,'Name',TO_TIMESTAMP('2023-06-10 17:28:58','YYYY-MM-DD HH24:MI:SS'),'N',0,'Name',0,10,215803,'N','Y',100,0,200400,100,'N',0,TO_TIMESTAMP('2023-06-10 17:28:58','YYYY-MM-DD HH24:MI:SS'),200016,0,0,'Y','N',0,0,'L','Y','Y','N','X','F','C','N','Y','N','N','N','N','N','N','N','N','N','N','N',1,0,'N','Y','N','N','27039afc-be5b-495a-8c3f-1ea07dfbbab6','N','Y','N')
;

-- Jun 10, 2023, 5:28:59 PM CEST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,PrintName,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,IsNextPage,IsFixedWidth,IsMaxCalc,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc,IsPrintBarcodeText,IsPrintInstanceAttributes) VALUES (30,'Alternate Test UU',TO_TIMESTAMP('2023-06-10 17:28:58','YYYY-MM-DD HH24:MI:SS'),'N',0,'Alternate Test UU',0,0,215804,'N','Y',100,0,200401,100,'N',0,TO_TIMESTAMP('2023-06-10 17:28:58','YYYY-MM-DD HH24:MI:SS'),200016,0,0,'Y','N',0,0,'L','N','N','N','X','F','C','N','N','N','N','N','N','N','N','N','N','N','N','N',1,0,'N','Y','N','N','c8dd6f7f-3e84-441d-b09d-5d208ca58942','N','Y','N')
;

-- Jun 10, 2023, 5:28:59 PM CEST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,PrintName,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,IsNextPage,IsFixedWidth,IsMaxCalc,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc,IsPrintBarcodeText,IsPrintInstanceAttributes) VALUES (40,'Multi Test UU',TO_TIMESTAMP('2023-06-10 17:28:59','YYYY-MM-DD HH24:MI:SS'),'N',0,'Multi Test UU',0,0,215809,'N','Y',100,0,200402,100,'N',0,TO_TIMESTAMP('2023-06-10 17:28:59','YYYY-MM-DD HH24:MI:SS'),200016,0,0,'Y','N',0,0,'L','N','N','N','X','F','C','N','N','N','N','N','N','N','N','N','N','N','N','N',1,0,'N','Y','N','N','8f140fde-3690-40d2-b59d-43925a6a5fd6','N','Y','N')
;

-- Jun 10, 2023, 5:28:59 PM CEST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,PrintName,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,IsNextPage,IsFixedWidth,IsMaxCalc,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc,IsPrintBarcodeText,IsPrintInstanceAttributes) VALUES (50,'TestUUDet_UU',TO_TIMESTAMP('2023-06-10 17:28:59','YYYY-MM-DD HH24:MI:SS'),'N',0,'TestUUDet_UU',0,0,215802,'N','Y',100,0,200403,100,'N',0,TO_TIMESTAMP('2023-06-10 17:28:59','YYYY-MM-DD HH24:MI:SS'),200016,0,0,'Y','N',0,0,'L','N','N','N','X','F','C','N','N','N','N','N','N','N','N','N','N','N','N','N',1,0,'N','Y','N','N','ffb87f00-8fff-4aaf-a293-beb25b2c17a9','N','Y','N')
;

-- Jun 10, 2023, 5:29:00 PM CEST
INSERT INTO AD_PrintFormat (Updated,CreatedBy,IsTableBased,IsActive,IsStandardHeaderFooter,AD_PrintFont_ID,AD_Table_ID,IsForm,HeaderMargin,UpdatedBy,AD_PrintColor_ID,Created,Name,FooterMargin,AD_Client_ID,AD_PrintPaper_ID,AD_Org_ID,AD_PrintFormat_ID,IsDefault,AD_PrintFormat_UU,IsBreakPagePerRecord) VALUES (TO_TIMESTAMP('2023-06-10 17:28:59','YYYY-MM-DD HH24:MI:SS'),100,'Y','Y','Y',130,200383,'Y',0,100,100,TO_TIMESTAMP('2023-06-10 17:28:59','YYYY-MM-DD HH24:MI:SS'),'TestUU Print Format',0,0,100,0,200017,'N','44b67140-a8da-49df-8bc6-6a696ff85edb','Y')
;

-- Jun 10, 2023, 5:29:00 PM CEST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,PrintName,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,IsNextPage,IsFixedWidth,IsMaxCalc,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc,IsPrintBarcodeText,IsPrintInstanceAttributes) VALUES (0,'Test UU',TO_TIMESTAMP('2023-06-10 17:29:00','YYYY-MM-DD HH24:MI:SS'),'N',0,'Test UU',0,0,215785,'N','Y',100,0,200404,100,'N',0,TO_TIMESTAMP('2023-06-10 17:29:00','YYYY-MM-DD HH24:MI:SS'),200017,0,0,'Y','N',0,0,'L','N','N','N','X','F','C','N','N','N','N','N','N','N','N','N','N','N','N','N',1,0,'N','Y','N','N','f5fce7a0-eb52-4cce-a31d-94a6fdd3b355','N','Y','N')
;

-- Jun 10, 2023, 5:29:00 PM CEST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,PrintName,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,IsNextPage,IsFixedWidth,IsMaxCalc,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc,IsPrintBarcodeText,IsPrintInstanceAttributes) VALUES (0,'Organization',TO_TIMESTAMP('2023-06-10 17:29:00','YYYY-MM-DD HH24:MI:SS'),'N',0,'Organization',0,0,215779,'N','Y',100,0,200405,100,'N',0,TO_TIMESTAMP('2023-06-10 17:29:00','YYYY-MM-DD HH24:MI:SS'),200017,0,0,'Y','N',0,0,'L','N','N','N','X','F','C','N','N','N','N','N','N','N','N','N','N','N','N','N',1,0,'N','Y','N','N','fa2ce6fb-9314-4c81-822d-232def5e5d71','N','Y','N')
;

-- Jun 10, 2023, 5:29:01 PM CEST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,PrintName,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,IsNextPage,IsFixedWidth,IsMaxCalc,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc,IsPrintBarcodeText,IsPrintInstanceAttributes) VALUES (0,'Tenant',TO_TIMESTAMP('2023-06-10 17:29:00','YYYY-MM-DD HH24:MI:SS'),'N',0,'Tenant',0,0,215778,'N','Y',100,0,200406,100,'N',0,TO_TIMESTAMP('2023-06-10 17:29:00','YYYY-MM-DD HH24:MI:SS'),200017,0,0,'Y','N',0,0,'L','N','N','N','X','F','C','N','N','N','N','N','N','N','N','N','N','N','N','N',1,0,'N','Y','N','N','2ad4b8ce-229f-4e9d-bcb1-490394b76b36','N','Y','N')
;

-- Jun 10, 2023, 5:29:01 PM CEST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,PrintName,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,IsNextPage,IsFixedWidth,IsMaxCalc,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc,IsPrintBarcodeText,IsPrintInstanceAttributes) VALUES (0,'Active',TO_TIMESTAMP('2023-06-10 17:29:01','YYYY-MM-DD HH24:MI:SS'),'N',0,'Active',0,0,215784,'N','Y',100,0,200407,100,'N',0,TO_TIMESTAMP('2023-06-10 17:29:01','YYYY-MM-DD HH24:MI:SS'),200017,0,0,'Y','N',0,0,'L','N','N','N','X','F','C','N','N','N','N','N','N','N','N','N','N','N','N','N',1,0,'N','Y','N','N','ba512d33-5da1-4d20-9a6e-1749cc199caf','N','Y','N')
;

-- Jun 10, 2023, 5:29:02 PM CEST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,YSpace,SortNo,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,AD_PrintColor_ID,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,AD_PrintFont_ID,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,BelowColumn,IsNextPage,IsFixedWidth,IsMaxCalc,RunningTotalLines,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc,IsPrintBarcodeText,IsPrintInstanceAttributes) VALUES (10,'Test Print Format for UUID Based Table',TO_TIMESTAMP('2023-06-10 17:29:01','YYYY-MM-DD HH24:MI:SS'),'Y',0,0,0,'N','N',100,0,200408,100,'N',10,100,TO_TIMESTAMP('2023-06-10 17:29:01','YYYY-MM-DD HH24:MI:SS'),200017,0,0,129,'Y','Y',0,70,'D','Y','N','N','X','T','C','N','N','N','N','N',0,'N','N','N',20,'N','N','N','N','N',1,0,'N','N','N','N','b3023947-0014-4657-a1cc-9952453cc9da','N','Y','N')
;

-- Jun 10, 2023, 5:29:02 PM CEST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,PrintName,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,IsNextPage,IsFixedWidth,IsMaxCalc,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc,IsPrintBarcodeText,IsPrintInstanceAttributes) VALUES (20,'Name',TO_TIMESTAMP('2023-06-10 17:29:02','YYYY-MM-DD HH24:MI:SS'),'N',0,'Name: ',0,0,215787,'N','N',100,0,200409,100,'N',50,TO_TIMESTAMP('2023-06-10 17:29:02','YYYY-MM-DD HH24:MI:SS'),200017,0,0,'Y','N',0,70,'L','Y','N','N','X','F','C','N','N','N','N','N','N','N','N','N','N','N','N','N',1,0,'N','Y','N','N','76c7238b-246b-4671-be0d-37f16d8703e5','N','Y','N')
;

-- Jun 10, 2023, 5:29:02 PM CEST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,PrintName,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,IsNextPage,IsFixedWidth,IsMaxCalc,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc,IsPrintBarcodeText,IsPrintInstanceAttributes) VALUES (20,'Search Key',TO_TIMESTAMP('2023-06-10 17:29:02','YYYY-MM-DD HH24:MI:SS'),'N',0,'Search Key: ',0,0,215786,'N','N',100,0,200410,100,'N',30,TO_TIMESTAMP('2023-06-10 17:29:02','YYYY-MM-DD HH24:MI:SS'),200017,0,0,'Y','N',0,70,'L','Y','N','N','X','F','C','N','N','N','N','N','N','N','N','N','N','N','N','N',1,0,'N','Y','N','N','25b9320b-e435-4941-b4b9-bd9203385b33','N','Y','N')
;

-- Jun 10, 2023, 5:29:03 PM CEST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,PrintName,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,IsNextPage,IsFixedWidth,IsMaxCalc,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc,IsPrintBarcodeText,IsPrintInstanceAttributes) VALUES (30,'Description',TO_TIMESTAMP('2023-06-10 17:29:03','YYYY-MM-DD HH24:MI:SS'),'N',0,'Description: ',0,0,215788,'N','N',100,0,200411,100,'N',70,TO_TIMESTAMP('2023-06-10 17:29:03','YYYY-MM-DD HH24:MI:SS'),200017,0,0,'Y','N',0,70,'L','Y','N','N','X','F','C','N','N','N','N','N','N','N','N','N','N','N','N','N',1,0,'N','Y','N','N','ea793329-5def-472c-8054-6c7f46acaf09','N','Y','N')
;

-- Jun 10, 2023, 5:29:03 PM CEST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,PrintName,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,IsNextPage,IsFixedWidth,IsMaxCalc,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc,IsPrintBarcodeText,IsPrintInstanceAttributes) VALUES (40,'Comment/Help',TO_TIMESTAMP('2023-06-10 17:29:03','YYYY-MM-DD HH24:MI:SS'),'N',0,'Comment: ',0,0,215789,'N','N',100,0,200412,100,'N',90,TO_TIMESTAMP('2023-06-10 17:29:03','YYYY-MM-DD HH24:MI:SS'),200017,0,0,'Y','N',0,70,'L','Y','N','N','X','F','C','N','N','N','N','N','N','N','N','N','N','N','N','N',1,0,'N','Y','N','N','ebd17120-96e7-4b12-be6f-e49c44210dae','N','Y','N')
;

-- Jun 10, 2023, 5:29:04 PM CEST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,AD_PrintFormatChild_ID,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,AD_PrintColor_ID,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,AD_PrintFont_ID,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,BelowColumn,IsNextPage,IsFixedWidth,IsMaxCalc,RunningTotalLines,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc,IsPrintBarcodeText,IsPrintInstanceAttributes) VALUES (60,'Detail',TO_TIMESTAMP('2023-06-10 17:29:03','YYYY-MM-DD HH24:MI:SS'),'Y',0,200016,0,0,215785,'N','Y',100,0,200413,100,'N',0,100,TO_TIMESTAMP('2023-06-10 17:29:03','YYYY-MM-DD HH24:MI:SS'),200017,0,0,130,'Y','Y',0,0,'D','Y','N','N','X','P','C','N','N','N','N','N',0,'N','N','N',20,'N','N','N','N','N',1,0,'N','N','N','N','7c7eb707-29bb-4950-96d7-b06c93122ac2','N','Y','N')
;

-- Jun 10, 2023, 5:29:04 PM CEST
INSERT INTO AD_Process (AD_Process_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,IsReport,Value,IsDirectPrint,AccessLevel,EntityType,Statistic_Count,Statistic_Seconds,AD_PrintFormat_ID,IsBetaFunctionality,ShowHelp,CopyFromProcess,AD_Process_UU,AllowMultipleExecution) VALUES (200153,0,0,'Y',TO_TIMESTAMP('2023-06-10 17:29:04','YYYY-MM-DD HH24:MI:SS'),100,TO_TIMESTAMP('2023-06-10 17:29:04','YYYY-MM-DD HH24:MI:SS'),100,'TestUU Form Report','Y','TestUU Form Report','N','7','D',5,21,200017,'N','Y','N','75f5cbfa-5ac5-4438-98bf-82115d2d5981','P')
;

-- Jun 10, 2023, 5:30:29 PM CEST
UPDATE AD_Tab SET AD_Process_ID=200153,Updated=TO_TIMESTAMP('2023-06-10 17:30:29','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Tab_ID=200348
;

-- Jun 10, 2023, 5:31:48 PM CEST
UPDATE TestUU SET Description='Lorem ipsum dolor sit amet', Help='consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut',Updated=TO_TIMESTAMP('2023-06-10 17:31:48','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE TestUU_UU='8858ecc2-cf1d-405f-987f-793536037e76'
;

-- Jun 10, 2023, 5:32:02 PM CEST
INSERT INTO TestUUDet (AD_Client_ID,AD_Org_ID,Created,CreatedBy,Updated,UpdatedBy,IsActive,TestUUDet_UU,Name,TestUU_UU) VALUES (11,0,TO_TIMESTAMP('2023-06-10 17:32:02','YYYY-MM-DD HH24:MI:SS'),100,TO_TIMESTAMP('2023-06-10 17:32:02','YYYY-MM-DD HH24:MI:SS'),100,'Y','d1f6b029-7d24-4ec6-bfc7-99d5a1e997c2','Detail One','8858ecc2-cf1d-405f-987f-793536037e76')
;

-- Jun 10, 2023, 5:32:09 PM CEST
INSERT INTO TestUUDet (AD_Client_ID,AD_Org_ID,Created,CreatedBy,Updated,UpdatedBy,IsActive,TestUUDet_UU,Name,TestUU_UU) VALUES (11,0,TO_TIMESTAMP('2023-06-10 17:32:09','YYYY-MM-DD HH24:MI:SS'),100,TO_TIMESTAMP('2023-06-10 17:32:09','YYYY-MM-DD HH24:MI:SS'),100,'Y','b341e80b-841c-41c8-9643-d4299155db09','Detail Two','8858ecc2-cf1d-405f-987f-793536037e76')
;

