-- IDEMPIERE-5728 Irrelevant No key Found warning logs
SELECT register_migration_script('202305181311_IDEMPIERE-5728.sql') FROM dual;

SET SQLBLANKLINES ON
SET DEFINE OFF

-- May 18, 2023, 1:11:39 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217679,'fe608bcf-7c87-430d-9f67-04352735ae1c',TO_TIMESTAMP('2023-05-18 13:11:39','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:11:39','YYYY-MM-DD HH24:MI:SS'),100,200199,'RV_Unprocessed_UU','gl_journal.gl_journal_uu',180)
;

-- May 18, 2023, 1:11:51 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217680,'5e64da5b-8c66-4981-bf28-01ce516b063d',TO_TIMESTAMP('2023-05-18 13:11:51','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:11:51','YYYY-MM-DD HH24:MI:SS'),100,200200,'RV_Unprocessed_UU','c_invoice.c_invoice_uu',180)
;

-- May 18, 2023, 1:12:45 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217681,'82aeed71-8389-4ad8-8da3-a484d5cb1835',TO_TIMESTAMP('2023-05-18 13:12:45','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:12:45','YYYY-MM-DD HH24:MI:SS'),100,200201,'RV_Unprocessed_UU','m_inout.m_inout_uu',180)
;

-- May 18, 2023, 1:13:08 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217682,'97b73b04-05f5-48dc-8ff6-716753ab4aa5',TO_TIMESTAMP('2023-05-18 13:13:07','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:13:07','YYYY-MM-DD HH24:MI:SS'),100,200202,'RV_Unprocessed_UU','m_inventory.m_inventory_uu',180)
;

-- May 18, 2023, 1:13:24 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217683,'d614004d-4f08-4589-9501-b494111dc14c',TO_TIMESTAMP('2023-05-18 13:13:23','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:13:23','YYYY-MM-DD HH24:MI:SS'),100,200203,'RV_Unprocessed_UU','m_movement.m_movement_uu',180)
;

-- May 18, 2023, 1:13:39 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217684,'45ef5326-5d63-4ef3-9ebf-deb9d130ecf1',TO_TIMESTAMP('2023-05-18 13:13:39','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:13:39','YYYY-MM-DD HH24:MI:SS'),100,200204,'RV_Unprocessed_UU','c_cash.c_cash_uu',180)
;

-- May 18, 2023, 1:13:53 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217685,'530ee593-7f24-410f-aaa2-5be787f6ff39',TO_TIMESTAMP('2023-05-18 13:13:53','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:13:53','YYYY-MM-DD HH24:MI:SS'),100,200205,'RV_Unprocessed_UU','c_payment.c_payment_uu',180)
;

-- May 18, 2023, 1:14:12 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217686,'95fd7013-6696-49c4-ab3d-3c85d5e87607',TO_TIMESTAMP('2023-05-18 13:14:12','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:14:12','YYYY-MM-DD HH24:MI:SS'),100,200206,'RV_Unprocessed_UU','c_allocationhdr.c_allocationhdr_uu',180)
;

-- May 18, 2023, 1:14:26 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217687,'58acdf86-ac8e-49b9-a304-c8a42b888651',TO_TIMESTAMP('2023-05-18 13:14:25','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:14:25','YYYY-MM-DD HH24:MI:SS'),100,200207,'RV_Unprocessed_UU','c_bankstatement.c_bankstatement_uu',180)
;

-- May 18, 2023, 1:14:36 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217688,'0256f3aa-c1af-4285-b471-6fd126203ec6',TO_TIMESTAMP('2023-05-18 13:14:36','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:14:36','YYYY-MM-DD HH24:MI:SS'),100,200208,'RV_Unprocessed_UU','c_order.c_order_uu',180)
;

-- May 18, 2023, 1:14:49 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217689,'7b70338e-582b-47ca-bcd1-43b2ee121886',TO_TIMESTAMP('2023-05-18 13:14:48','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:14:48','YYYY-MM-DD HH24:MI:SS'),100,200209,'RV_Unprocessed_UU','m_requisition.m_requisition_uu',180)
;

-- May 18, 2023, 1:48:52 PM CEST
CREATE OR REPLACE VIEW RV_Unprocessed(AD_Client_ID, AD_Org_ID, Created, CreatedBy, Updated, UpdatedBy, IsActive, DocumentNo, DateDoc, DateAcct, AD_Table_ID, Record_ID, IsSOTrx, Posted, Processing, Processed, DocStatus, RV_Unprocessed_UU) AS SELECT gl_journal.ad_client_id AS AD_Client_ID, gl_journal.ad_org_id AS AD_Org_ID, gl_journal.created AS Created, gl_journal.createdby AS CreatedBy, gl_journal.updated AS Updated, gl_journal.updatedby AS UpdatedBy, gl_journal.isactive AS IsActive, gl_journal.documentno AS DocumentNo, gl_journal.datedoc AS DateDoc, gl_journal.dateacct AS DateAcct, 224 AS AD_Table_ID, gl_journal.gl_journal_id AS Record_ID, 'N' AS IsSOTrx, gl_journal.posted AS Posted, gl_journal.processing AS Processing, gl_journal.processed AS Processed, gl_journal.docstatus AS DocStatus, gl_journal.gl_journal_uu AS RV_Unprocessed_UU FROM gl_journal WHERE gl_journal.docstatus NOT IN ('CO', 'CL', 'VO', 'RE') UNION SELECT c_invoice.ad_client_id AS AD_Client_ID, c_invoice.ad_org_id AS AD_Org_ID, c_invoice.created AS Created, c_invoice.createdby AS CreatedBy, c_invoice.updated AS Updated, c_invoice.updatedby AS UpdatedBy, c_invoice.isactive AS IsActive, c_invoice.documentno AS DocumentNo, c_invoice.dateinvoiced AS DateDoc, c_invoice.dateacct AS DateAcct, 318 AS AD_Table_ID, c_invoice.c_invoice_id AS Record_ID, c_invoice.issotrx AS IsSOTrx, c_invoice.posted AS Posted, c_invoice.processing AS Processing, c_invoice.processed AS Processed, c_invoice.docstatus AS DocStatus, c_invoice.c_invoice_uu AS RV_Unprocessed_UU FROM c_invoice WHERE c_invoice.docstatus NOT IN ('CO', 'CL', 'VO', 'RE') UNION SELECT m_inout.ad_client_id AS AD_Client_ID, m_inout.ad_org_id AS AD_Org_ID, m_inout.created AS Created, m_inout.createdby AS CreatedBy, m_inout.updated AS Updated, m_inout.updatedby AS UpdatedBy, m_inout.isactive AS IsActive, m_inout.documentno AS DocumentNo, m_inout.movementdate AS DateDoc, m_inout.dateacct AS DateAcct, 319 AS AD_Table_ID, m_inout.m_inout_id AS Record_ID, m_inout.issotrx AS IsSOTrx, m_inout.posted AS Posted, m_inout.processing AS Processing, m_inout.processed AS Processed, m_inout.docstatus AS DocStatus, m_inout.m_inout_uu AS RV_Unprocessed_UU FROM m_inout WHERE m_inout.docstatus NOT IN ('CO', 'CL', 'VO', 'RE')
UNION SELECT m_inventory.ad_client_id AS AD_Client_ID, m_inventory.ad_org_id AS AD_Org_ID, m_inventory.created AS Created, m_inventory.createdby AS CreatedBy, m_inventory.updated AS Updated, m_inventory.updatedby AS UpdatedBy, m_inventory.isactive AS IsActive, m_inventory.documentno AS DocumentNo, m_inventory.movementdate AS DateDoc, m_inventory.movementdate AS DateAcct, 321 AS AD_Table_ID, m_inventory.m_inventory_id AS Record_ID, 'N' AS IsSOTrx, m_inventory.posted AS Posted, m_inventory.processing AS Processing, m_inventory.processed AS Processed, m_inventory.docstatus AS DocStatus, m_inventory.m_inventory_uu AS RV_Unprocessed_UU FROM m_inventory WHERE m_inventory.docstatus NOT IN ('CO', 'CL', 'VO', 'RE') UNION SELECT m_movement.ad_client_id AS AD_Client_ID, m_movement.ad_org_id AS AD_Org_ID, m_movement.created AS Created, m_movement.createdby AS CreatedBy, m_movement.updated AS Updated, m_movement.updatedby AS UpdatedBy, m_movement.isactive AS IsActive, m_movement.documentno AS DocumentNo, m_movement.movementdate AS DateDoc, m_movement.movementdate AS DateAcct, 323 AS AD_Table_ID, m_movement.m_movement_id AS Record_ID, 'N' AS IsSOTrx, m_movement.posted AS Posted, m_movement.processing AS Processing, m_movement.processed AS Processed, m_movement.docstatus AS DocStatus, m_movement.m_movement_uu AS RV_Unprocessed_UU FROM m_movement WHERE m_movement.docstatus NOT IN ('CO', 'CL', 'VO', 'RE') UNION SELECT c_cash.ad_client_id AS AD_Client_ID, c_cash.ad_org_id AS AD_Org_ID, c_cash.created AS Created, c_cash.createdby AS CreatedBy, c_cash.updated AS Updated, c_cash.updatedby AS UpdatedBy, c_cash.isactive AS IsActive, c_cash.name AS DocumentNo, c_cash.statementdate AS DateDoc, c_cash.dateacct AS DateAcct, 407 AS AD_Table_ID, c_cash.c_cash_id AS Record_ID, 'N' AS IsSOTrx, c_cash.posted AS Posted, c_cash.processing AS Processing, c_cash.processed AS Processed, c_cash.docstatus AS DocStatus, c_cash.c_cash_uu AS RV_Unprocessed_UU FROM c_cash WHERE c_cash.docstatus NOT IN ('CO', 'CL', 'VO', 'RE')
UNION SELECT c_payment.ad_client_id AS AD_Client_ID, c_payment.ad_org_id AS AD_Org_ID, c_payment.created AS Created, c_payment.createdby AS CreatedBy, c_payment.updated AS Updated, c_payment.updatedby AS UpdatedBy, c_payment.isactive AS IsActive, c_payment.documentno AS DocumentNo, c_payment.datetrx AS DateDoc, c_payment.datetrx AS DateAcct, 335 AS AD_Table_ID, c_payment.c_payment_id AS Record_ID, 'N' AS IsSOTrx, c_payment.posted AS Posted, c_payment.processing AS Processing, c_payment.processed AS Processed, c_payment.docstatus AS DocStatus, c_payment.c_payment_uu AS RV_Unprocessed_UU FROM c_payment WHERE c_payment.docstatus NOT IN ('CO', 'CL', 'VO', 'RE') UNION SELECT c_allocationhdr.ad_client_id AS AD_Client_ID, c_allocationhdr.ad_org_id AS AD_Org_ID, c_allocationhdr.created AS Created, c_allocationhdr.createdby AS CreatedBy, c_allocationhdr.updated AS Updated, c_allocationhdr.updatedby AS UpdatedBy, c_allocationhdr.isactive AS IsActive, c_allocationhdr.documentno AS DocumentNo, c_allocationhdr.datetrx AS DateDoc, c_allocationhdr.datetrx AS DateAcct, 735 AS AD_Table_ID, c_allocationhdr.c_allocationhdr_id AS Record_ID, 'N' AS IsSOTrx, c_allocationhdr.posted AS Posted, c_allocationhdr.processing AS Processing, c_allocationhdr.processed AS Processed, c_allocationhdr.docstatus AS DocStatus, c_allocationhdr.c_allocationhdr_uu AS RV_Unprocessed_UU FROM c_allocationhdr WHERE c_allocationhdr.docstatus NOT IN ('CO', 'CL', 'VO', 'RE') UNION SELECT c_bankstatement.ad_client_id AS AD_Client_ID, c_bankstatement.ad_org_id AS AD_Org_ID, c_bankstatement.created AS Created, c_bankstatement.createdby AS CreatedBy, c_bankstatement.updated AS Updated, c_bankstatement.updatedby AS UpdatedBy, c_bankstatement.isactive AS IsActive, c_bankstatement.name AS DocumentNo, c_bankstatement.statementdate AS DateDoc, c_bankstatement.statementdate AS DateAcct, 392 AS AD_Table_ID, c_bankstatement.c_bankstatement_id AS Record_ID, 'N' AS IsSOTrx, c_bankstatement.posted AS Posted, c_bankstatement.processing AS Processing, c_bankstatement.processed AS Processed, c_bankstatement.docstatus AS DocStatus, c_bankstatement.c_bankstatement_uu AS RV_Unprocessed_UU FROM c_bankstatement WHERE c_bankstatement.docstatus NOT IN ('CO', 'CL', 'VO', 'RE')
UNION SELECT c_order.ad_client_id AS AD_Client_ID, c_order.ad_org_id AS AD_Org_ID, c_order.created AS Created, c_order.createdby AS CreatedBy, c_order.updated AS Updated, c_order.updatedby AS UpdatedBy, c_order.isactive AS IsActive, c_order.documentno AS DocumentNo, c_order.dateordered AS DateDoc, c_order.dateacct AS DateAcct, 259 AS AD_Table_ID, c_order.c_order_id AS Record_ID, c_order.issotrx AS IsSOTrx, c_order.posted AS Posted, c_order.processing AS Processing, c_order.processed AS Processed, c_order.docstatus AS DocStatus, c_order.c_order_uu AS RV_Unprocessed_UU FROM c_order WHERE c_order.docstatus NOT IN ('CO', 'CL', 'VO', 'RE') UNION SELECT m_requisition.ad_client_id AS AD_Client_ID, m_requisition.ad_org_id AS AD_Org_ID, m_requisition.created AS Created, m_requisition.createdby AS CreatedBy, m_requisition.updated AS Updated, m_requisition.updatedby AS UpdatedBy, m_requisition.isactive AS IsActive, m_requisition.documentno AS DocumentNo, m_requisition.datedoc AS DateDoc, m_requisition.datedoc AS DateAcct, 702 AS AD_Table_ID, m_requisition.m_requisition_id AS Record_ID, 'N' AS IsSOTrx, m_requisition.posted AS Posted, m_requisition.processing AS Processing, m_requisition.processed AS Processed, m_requisition.docstatus AS DocStatus, m_requisition.m_requisition_uu AS RV_Unprocessed_UU FROM m_requisition WHERE m_requisition.docstatus NOT IN ('CO', 'CL', 'VO', 'RE')
;

-- May 18, 2023, 1:50:07 PM CEST
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,EntityType,AD_Element_UU) VALUES (203810,0,0,'Y',TO_TIMESTAMP('2023-05-18 13:50:07','YYYY-MM-DD HH24:MI:SS'),100,TO_TIMESTAMP('2023-05-18 13:50:07','YYYY-MM-DD HH24:MI:SS'),100,'RV_Unprocessed_UU','RV_Unprocessed_UU','RV_Unprocessed_UU','D','0583ffc1-3a83-4111-8c16-9639a5fdd219')
;

-- May 18, 2023, 1:50:07 PM CEST
INSERT INTO AD_Column (AD_Column_ID,Version,Name,AD_Table_ID,ColumnName,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,IsEncrypted,AD_Reference_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsAlwaysUpdateable,AD_Column_UU,IsToolbarButton) VALUES (215838,0.0,'RV_Unprocessed_UU',53221,'RV_Unprocessed_UU',36,'N','N','N','N','N','N',10,0,0,'Y',TO_TIMESTAMP('2023-05-18 13:50:07','YYYY-MM-DD HH24:MI:SS'),100,TO_TIMESTAMP('2023-05-18 13:50:07','YYYY-MM-DD HH24:MI:SS'),100,203810,'N','N','D','N','ca416980-44cf-4353-8237-95e0d0a2e548','N')
;

-- May 18, 2023, 1:51:41 PM CEST
INSERT INTO AD_Field (AD_Field_ID,Name,AD_Tab_ID,AD_Column_ID,IsDisplayed,DisplayLength,IsSameLine,IsHeading,IsFieldOnly,IsEncrypted,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,IsReadOnly,IsCentrallyMaintained,EntityType,AD_Field_UU,IsDisplayedGrid,ColumnSpan) VALUES (207623,'RV_Unprocessed_UU',53238,215838,'N',36,'N','N','N','N',0,0,'Y',TO_TIMESTAMP('2023-05-18 13:51:40','YYYY-MM-DD HH24:MI:SS'),100,TO_TIMESTAMP('2023-05-18 13:51:40','YYYY-MM-DD HH24:MI:SS'),100,'N','Y','D','47b8f778-e2ec-4cde-a9a4-68baba5da1da','N',2)
;

-- May 18, 2023, 1:51:48 PM CEST
INSERT INTO AD_Field (AD_Field_ID,Name,AD_Tab_ID,AD_Column_ID,IsDisplayed,DisplayLength,IsSameLine,IsHeading,IsFieldOnly,IsEncrypted,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,IsReadOnly,IsCentrallyMaintained,EntityType,AD_Field_UU,IsDisplayedGrid,ColumnSpan) VALUES (207624,'RV_Unprocessed_UU',53239,215838,'N',36,'N','N','N','N',0,0,'Y',TO_TIMESTAMP('2023-05-18 13:51:47','YYYY-MM-DD HH24:MI:SS'),100,TO_TIMESTAMP('2023-05-18 13:51:47','YYYY-MM-DD HH24:MI:SS'),100,'N','Y','D','a05dafc1-ef27-46cf-a4df-14f9dae0f958','N',2)
;

-- May 18, 2023, 1:55:19 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217690,'64e69a95-631a-4fc9-8b41-2b060c22623f',TO_TIMESTAMP('2023-05-18 13:55:19','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:55:19','YYYY-MM-DD HH24:MI:SS'),100,200184,'GL_Journal_UU','gl_journal.gl_journal_uu',200)
;

-- May 18, 2023, 1:55:59 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217691,'8a443022-cc4f-49fc-8b8f-403bbfa36add',TO_TIMESTAMP('2023-05-18 13:55:58','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:55:58','YYYY-MM-DD HH24:MI:SS'),100,200185,'RV_UnPosted_UU','pi.c_projectissue_uu',200)
;

-- May 18, 2023, 1:56:20 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217692,'459bbf75-e5e7-47e3-9db6-3b58787b409b',TO_TIMESTAMP('2023-05-18 13:56:20','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:56:20','YYYY-MM-DD HH24:MI:SS'),100,200186,'RV_UnPosted_UU','c_invoice.c_invoice_uu',200)
;

-- May 18, 2023, 1:57:22 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217693,'029bebb9-c13c-4ab8-952f-0afc0e2a4e7e',TO_TIMESTAMP('2023-05-18 13:57:22','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:57:22','YYYY-MM-DD HH24:MI:SS'),100,200187,'RV_UnPosted_UU','m_inout.m_inout_uu',200)
;

-- May 18, 2023, 1:57:38 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217694,'628c2a1a-de0d-4c12-a6d6-9816d1c8638a',TO_TIMESTAMP('2023-05-18 13:57:37','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:57:37','YYYY-MM-DD HH24:MI:SS'),100,200188,'RV_UnPosted_UU','m_inventory.m_inventory_uu',200)
;

-- May 18, 2023, 1:57:53 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217695,'c1bc5cbd-424a-47b9-b7b3-aeaf3f52f27f',TO_TIMESTAMP('2023-05-18 13:57:53','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:57:53','YYYY-MM-DD HH24:MI:SS'),100,200189,'RV_UnPosted_UU','m_movement.m_movement_uu',200)
;

-- May 18, 2023, 1:58:44 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217696,'4ec07ee7-567c-4d1a-9d6f-22eaa592fd5b',TO_TIMESTAMP('2023-05-18 13:58:43','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:58:43','YYYY-MM-DD HH24:MI:SS'),100,200192,'RV_UnPosted_UU','c_payment.c_payment_uu',200)
;

-- May 18, 2023, 1:59:00 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217697,'af3b3f09-b6dc-43f5-9bda-9f1d31b2f202',TO_TIMESTAMP('2023-05-18 13:59:00','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:59:00','YYYY-MM-DD HH24:MI:SS'),100,200193,'RV_UnPosted_UU','c_allocationhdr.c_allocationhdr_uu',200)
;

-- May 18, 2023, 1:59:16 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217698,'42310804-d158-49d5-8944-94276dfd1f1f',TO_TIMESTAMP('2023-05-18 13:59:16','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:59:16','YYYY-MM-DD HH24:MI:SS'),100,200194,'RV_UnPosted_UU','c_bankstatement.c_bankstatement_uu',200)
;

-- May 18, 2023, 1:59:31 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217699,'359e5a56-fd78-437d-9dd0-210324366c94',TO_TIMESTAMP('2023-05-18 13:59:30','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:59:30','YYYY-MM-DD HH24:MI:SS'),100,200195,'RV_UnPosted_UU','m_matchinv.m_matchinv_uu',200)
;

-- May 18, 2023, 1:59:42 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217700,'1593b15b-70df-4556-9608-86f9894fae90',TO_TIMESTAMP('2023-05-18 13:59:42','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:59:42','YYYY-MM-DD HH24:MI:SS'),100,200196,'RV_UnPosted_UU','m_matchpo.m_matchpo_uu',200)
;

-- May 18, 2023, 1:59:53 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217701,'78a89427-8d4f-4286-9a0e-ac07ca6abd22',TO_TIMESTAMP('2023-05-18 13:59:53','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 13:59:53','YYYY-MM-DD HH24:MI:SS'),100,200197,'RV_UnPosted_UU','c_order.c_order_uu',200)
;

-- May 18, 2023, 2:00:06 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217702,'b9893bd3-2e62-4502-8174-ecb2e88f8b6a',TO_TIMESTAMP('2023-05-18 14:00:05','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 14:00:05','YYYY-MM-DD HH24:MI:SS'),100,200198,'RV_UnPosted_UU','m_requisition.m_requisition_uu',200)
;

-- May 18, 2023, 2:03:29 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217703,'a784bd01-a1c9-4875-9f15-295d7087737e',TO_TIMESTAMP('2023-05-18 14:03:28','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 14:03:28','YYYY-MM-DD HH24:MI:SS'),100,200190,'RV_UnPosted_UU','m_production.m_production_uu',200)
;

-- May 18, 2023, 2:04:03 PM CEST
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217704,'ef4d1ad0-9184-4dfc-9b18-c875046110d4',TO_TIMESTAMP('2023-05-18 14:04:03','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2023-05-18 14:04:03','YYYY-MM-DD HH24:MI:SS'),100,200191,'RV_UnPosted_UU','c_cash.c_cash_uu',200)
;

-- May 18, 2023, 2:04:22 PM CEST
CREATE OR REPLACE VIEW RV_UnPosted(AD_Client_ID, AD_Org_ID, Created, CreatedBy, Updated, UpdatedBy, IsActive, DocumentNo, DateDoc, DateAcct, AD_Table_ID, Record_ID, IsSOTrx, Posted, Processing, Processed, DocStatus, ProcessedOn, DocBaseType, RV_UnPosted_UU) AS SELECT gl_journal.ad_client_id AS AD_Client_ID, gl_journal.ad_org_id AS AD_Org_ID, gl_journal.created AS Created, gl_journal.createdby AS CreatedBy, gl_journal.updated AS Updated, gl_journal.updatedby AS UpdatedBy, gl_journal.isactive AS IsActive, gl_journal.documentno AS DocumentNo, gl_journal.datedoc AS DateDoc, gl_journal.dateacct AS DateAcct, 224 AS AD_Table_ID, gl_journal.gl_journal_id AS Record_ID, 'N' AS IsSOTrx, gl_journal.posted AS Posted, gl_journal.processing AS Processing, gl_journal.processed AS Processed, gl_journal.docstatus AS DocStatus, gl_journal.processedon AS ProcessedOn, dt.DocBaseType AS DocBaseType, gl_journal.gl_journal_uu AS RV_UnPosted_UU FROM gl_journal
JOIN C_DocType dt ON (dt.C_DocType_ID = gl_journal.C_DocType_ID) WHERE gl_journal.posted <> 'Y' AND gl_journal.docstatus <> 'VO' UNION SELECT pi.ad_client_id AS AD_Client_ID, pi.ad_org_id AS AD_Org_ID, pi.created AS Created, pi.createdby AS CreatedBy, pi.updated AS Updated, pi.updatedby AS UpdatedBy, pi.isactive AS IsActive, (p.name || '_') || pi.line AS DocumentNo, pi.movementdate AS DateDoc, pi.movementdate AS DateAcct, 623 AS AD_Table_ID, pi.c_projectissue_id AS Record_ID, 'N' AS IsSOTrx, pi.posted AS Posted, pi.processing AS Processing, pi.processed AS Processed, 'CO' AS DocStatus, pi.processedon AS ProcessedOn, 'PJI' AS DocBaseType, pi.c_projectissue_uu AS RV_UnPosted_UU FROM c_projectissue pi
JOIN c_project p ON pi.c_project_id = p.c_project_id WHERE pi.posted <> 'Y' UNION SELECT c_invoice.ad_client_id AS AD_Client_ID, c_invoice.ad_org_id AS AD_Org_ID, c_invoice.created AS Created, c_invoice.createdby AS CreatedBy, c_invoice.updated AS Updated, c_invoice.updatedby AS UpdatedBy, c_invoice.isactive AS IsActive, c_invoice.documentno AS DocumentNo, c_invoice.dateinvoiced AS DateDoc, c_invoice.dateacct AS DateAcct, 318 AS AD_Table_ID, c_invoice.c_invoice_id AS Record_ID, c_invoice.issotrx AS IsSOTrx, c_invoice.posted AS Posted, c_invoice.processing AS Processing, c_invoice.processed AS Processed, c_invoice.docstatus AS DocStatus, c_invoice.processedon AS ProcessedOn, dt.DocBaseType AS DocBaseType, c_invoice.c_invoice_uu AS RV_UnPosted_UU FROM c_invoice
JOIN C_DocType dt ON (dt.C_DocType_ID = c_invoice.C_DocType_ID) WHERE c_invoice.posted <> 'Y' AND c_invoice.docstatus <> 'VO' UNION SELECT m_inout.ad_client_id AS AD_Client_ID, m_inout.ad_org_id AS AD_Org_ID, m_inout.created AS Created, m_inout.createdby AS CreatedBy, m_inout.updated AS Updated, m_inout.updatedby AS UpdatedBy, m_inout.isactive AS IsActive, m_inout.documentno AS DocumentNo, m_inout.movementdate AS DateDoc, m_inout.dateacct AS DateAcct, 319 AS AD_Table_ID, m_inout.m_inout_id AS Record_ID, m_inout.issotrx AS IsSOTrx, m_inout.posted AS Posted, m_inout.processing AS Processing, m_inout.processed AS Processed, m_inout.docstatus AS DocStatus, m_inout.processedon AS ProcessedOn, dt.DocBaseType AS DocBaseType, m_inout.m_inout_uu AS RV_UnPosted_UU FROM m_inout
JOIN C_DocType dt ON (dt.C_DocType_ID = m_inout.C_DocType_ID) WHERE m_inout.posted <> 'Y' AND m_inout.docstatus <> 'VO' UNION SELECT m_inventory.ad_client_id AS AD_Client_ID, m_inventory.ad_org_id AS AD_Org_ID, m_inventory.created AS Created, m_inventory.createdby AS CreatedBy, m_inventory.updated AS Updated, m_inventory.updatedby AS UpdatedBy, m_inventory.isactive AS IsActive, m_inventory.documentno AS DocumentNo, m_inventory.movementdate AS DateDoc, m_inventory.movementdate AS DateAcct, 321 AS AD_Table_ID, m_inventory.m_inventory_id AS Record_ID, 'N' AS IsSOTrx, m_inventory.posted AS Posted, m_inventory.processing AS Processing, m_inventory.processed AS Processed, m_inventory.docstatus AS DocStatus, m_inventory.processedon AS ProcessedOn, dt.DocBaseType AS DocBaseType, m_inventory.m_inventory_uu AS RV_UnPosted_UU FROM m_inventory
JOIN C_DocType dt ON (dt.C_DocType_ID = m_inventory.C_DocType_ID) WHERE m_inventory.posted <> 'Y' AND m_inventory.docstatus <> 'VO' UNION SELECT m_movement.ad_client_id AS AD_Client_ID, m_movement.ad_org_id AS AD_Org_ID, m_movement.created AS Created, m_movement.createdby AS CreatedBy, m_movement.updated AS Updated, m_movement.updatedby AS UpdatedBy, m_movement.isactive AS IsActive, m_movement.documentno AS DocumentNo, m_movement.movementdate AS DateDoc, m_movement.movementdate AS DateAcct, 323 AS AD_Table_ID, m_movement.m_movement_id AS Record_ID, 'N' AS IsSOTrx, m_movement.posted AS Posted, m_movement.processing AS Processing, m_movement.processed AS Processed, m_movement.docstatus AS DocStatus, m_movement.processedon AS ProcessedOn, dt.DocBaseType AS DocBaseType, m_movement.m_movement_uu AS RV_UnPosted_UU FROM m_movement
JOIN C_DocType dt ON (dt.C_DocType_ID = m_movement.C_DocType_ID) WHERE m_movement.posted <> 'Y' AND m_movement.docstatus <> 'VO' UNION SELECT m_production.ad_client_id AS AD_Client_ID, m_production.ad_org_id AS AD_Org_ID, m_production.created AS Created, m_production.createdby AS CreatedBy, m_production.updated AS Updated, m_production.updatedby AS UpdatedBy, m_production.isactive AS IsActive, m_production.documentno AS DocumentNo, m_production.movementdate AS DateDoc, m_production.movementdate AS DateAcct, 325 AS AD_Table_ID, m_production.m_production_id AS Record_ID, 'N' AS IsSOTrx, m_production.posted AS Posted, m_production.processing AS Processing, m_production.processed AS Processed, m_production.docstatus AS DocStatus, m_production.processedon AS ProcessedOn, 'MMP' AS DocBaseType, m_production.m_production_uu AS RV_UnPosted_UU FROM m_production WHERE m_production.posted <> 'Y' AND m_production.docstatus <> 'VO' UNION SELECT c_cash.ad_client_id AS AD_Client_ID, c_cash.ad_org_id AS AD_Org_ID, c_cash.created AS Created, c_cash.createdby AS CreatedBy, c_cash.updated AS Updated, c_cash.updatedby AS UpdatedBy, c_cash.isactive AS IsActive, c_cash.name AS DocumentNo, c_cash.statementdate AS DateDoc, c_cash.dateacct AS DateAcct, 407 AS AD_Table_ID, c_cash.c_cash_id AS Record_ID, 'N' AS IsSOTrx, c_cash.posted AS Posted, c_cash.processing AS Processing, c_cash.processed AS Processed, c_cash.docstatus AS DocStatus, c_cash.processedon AS ProcessedOn, 'CMC' AS DocBaseType, c_cash.c_cash_uu AS RV_UnPosted_UU FROM c_cash WHERE c_cash.posted <> 'Y' AND c_cash.docstatus <> 'VO' UNION SELECT c_payment.ad_client_id AS AD_Client_ID, c_payment.ad_org_id AS AD_Org_ID, c_payment.created AS Created, c_payment.createdby AS CreatedBy, c_payment.updated AS Updated, c_payment.updatedby AS UpdatedBy, c_payment.isactive AS IsActive, c_payment.documentno AS DocumentNo, c_payment.datetrx AS DateDoc, c_payment.dateacct AS DateAcct, 335 AS AD_Table_ID, c_payment.c_payment_id AS Record_ID, 'N' AS IsSOTrx, c_payment.posted AS Posted, c_payment.processing AS Processing, c_payment.processed AS Processed, c_payment.docstatus AS DocStatus, c_payment.processedon AS ProcessedOn, dt.DocBaseType AS DocBaseType, c_payment.c_payment_uu AS RV_UnPosted_UU FROM c_payment
JOIN C_DocType dt ON (dt.C_DocType_ID = c_payment.C_DocType_ID) WHERE c_payment.posted <> 'Y' AND c_payment.docstatus <> 'VO' UNION SELECT c_allocationhdr.ad_client_id AS AD_Client_ID, c_allocationhdr.ad_org_id AS AD_Org_ID, c_allocationhdr.created AS Created, c_allocationhdr.createdby AS CreatedBy, c_allocationhdr.updated AS Updated, c_allocationhdr.updatedby AS UpdatedBy, c_allocationhdr.isactive AS IsActive, c_allocationhdr.documentno AS DocumentNo, c_allocationhdr.datetrx AS DateDoc, c_allocationhdr.dateacct AS DateAcct, 735 AS AD_Table_ID, c_allocationhdr.c_allocationhdr_id AS Record_ID, 'N' AS IsSOTrx, c_allocationhdr.posted AS Posted, c_allocationhdr.processing AS Processing, c_allocationhdr.processed AS Processed, c_allocationhdr.docstatus AS DocStatus, c_allocationhdr.processedon AS ProcessedOn, dt.DocBaseType AS DocBaseType, c_allocationhdr.c_allocationhdr_uu AS RV_UnPosted_UU FROM c_allocationhdr
JOIN C_DocType dt ON (dt.C_DocType_ID = c_allocationhdr.C_DocType_ID) WHERE c_allocationhdr.posted <> 'Y' AND c_allocationhdr.docstatus <> 'VO' UNION SELECT c_bankstatement.ad_client_id AS AD_Client_ID, c_bankstatement.ad_org_id AS AD_Org_ID, c_bankstatement.created AS Created, c_bankstatement.createdby AS CreatedBy, c_bankstatement.updated AS Updated, c_bankstatement.updatedby AS UpdatedBy, c_bankstatement.isactive AS IsActive, c_bankstatement.name AS DocumentNo, c_bankstatement.statementdate AS DateDoc, c_bankstatement.statementdate AS DateAcct, 392 AS AD_Table_ID, c_bankstatement.c_bankstatement_id AS Record_ID, 'N' AS IsSOTrx, c_bankstatement.posted AS Posted, c_bankstatement.processing AS Processing, c_bankstatement.processed AS Processed, c_bankstatement.docstatus AS DocStatus, c_bankstatement.processedon AS ProcessedOn, 'CMB' AS DocBaseType, c_bankstatement.c_bankstatement_uu AS RV_UnPosted_UU FROM c_bankstatement WHERE c_bankstatement.posted <> 'Y' AND c_bankstatement.docstatus <> 'VO' UNION SELECT m_matchinv.ad_client_id AS AD_Client_ID, m_matchinv.ad_org_id AS AD_Org_ID, m_matchinv.created AS Created, m_matchinv.createdby AS CreatedBy, m_matchinv.updated AS Updated, m_matchinv.updatedby AS UpdatedBy, m_matchinv.isactive AS IsActive, m_matchinv.documentno AS DocumentNo, m_matchinv.datetrx AS DateDoc, m_matchinv.dateacct AS DateAcct, 472 AS AD_Table_ID, m_matchinv.m_matchinv_id AS Record_ID, 'N' AS IsSOTrx, m_matchinv.posted AS Posted, m_matchinv.processing AS Processing, m_matchinv.processed AS Processed, 'CO' AS DocStatus, m_matchinv.processedon AS ProcessedOn, 'MXI' AS DocBaseType, m_matchinv.m_matchinv_uu AS RV_UnPosted_UU FROM m_matchinv WHERE m_matchinv.posted <> 'Y' UNION SELECT m_matchpo.ad_client_id AS AD_Client_ID, m_matchpo.ad_org_id AS AD_Org_ID, m_matchpo.created AS Created, m_matchpo.createdby AS CreatedBy, m_matchpo.updated AS Updated, m_matchpo.updatedby AS UpdatedBy, m_matchpo.isactive AS IsActive, m_matchpo.documentno AS DocumentNo, m_matchpo.datetrx AS DateDoc, m_matchpo.dateacct AS DateAcct, 473 AS AD_Table_ID, m_matchpo.m_matchpo_id AS Record_ID, 'N' AS IsSOTrx, m_matchpo.posted AS Posted, m_matchpo.processing AS Processing, m_matchpo.processed AS Processed, 'CO' AS DocStatus, m_matchpo.processedon AS ProcessedOn, 'MXP' AS DocBaseType, m_matchpo.m_matchpo_uu AS RV_UnPosted_UU FROM m_matchpo WHERE m_matchpo.posted <> 'Y'
UNION SELECT c_order.ad_client_id AS AD_Client_ID, c_order.ad_org_id AS AD_Org_ID, c_order.created AS Created, c_order.createdby AS CreatedBy, c_order.updated AS Updated, c_order.updatedby AS UpdatedBy, c_order.isactive AS IsActive, c_order.documentno AS DocumentNo, c_order.dateordered AS DateDoc, c_order.dateacct AS DateAcct, 259 AS AD_Table_ID, c_order.c_order_id AS Record_ID, c_order.issotrx AS IsSOTrx, c_order.posted AS Posted, c_order.processing AS Processing, c_order.processed AS Processed, c_order.docstatus AS DocStatus, c_order.processedon AS ProcessedOn, dt.DocBaseType AS DocBaseType, c_order.c_order_uu AS RV_UnPosted_UU FROM c_order
JOIN C_DocType dt ON (dt.C_DocType_ID = c_order.C_DocType_ID) WHERE c_order.posted <> 'Y' AND c_order.docstatus <> 'VO' UNION SELECT m_requisition.ad_client_id AS AD_Client_ID, m_requisition.ad_org_id AS AD_Org_ID, m_requisition.created AS Created, m_requisition.createdby AS CreatedBy, m_requisition.updated AS Updated, m_requisition.updatedby AS UpdatedBy, m_requisition.isactive AS IsActive, m_requisition.documentno AS DocumentNo, m_requisition.datedoc AS DateDoc, m_requisition.datedoc AS DateAcct, 702 AS AD_Table_ID, m_requisition.m_requisition_id AS Record_ID, 'N' AS IsSOTrx, m_requisition.posted AS Posted, m_requisition.processing AS Processing, m_requisition.processed AS Processed, m_requisition.docstatus AS DocStatus, m_requisition.processedon AS ProcessedOn, dt.DocBaseType AS DocBaseType, m_requisition.m_requisition_uu AS RV_UnPosted_UU FROM m_requisition
JOIN C_DocType dt ON (dt.C_DocType_ID = m_requisition.C_DocType_ID) WHERE m_requisition.posted <> 'Y' AND m_requisition.docstatus <> 'VO'
;

-- May 18, 2023, 2:04:40 PM CEST
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,EntityType,AD_Element_UU) VALUES (203811,0,0,'Y',TO_TIMESTAMP('2023-05-18 14:04:39','YYYY-MM-DD HH24:MI:SS'),100,TO_TIMESTAMP('2023-05-18 14:04:39','YYYY-MM-DD HH24:MI:SS'),100,'RV_UnPosted_UU','RV_UnPosted_UU','RV_UnPosted_UU','D','25a2db91-811d-4042-ba13-54b684b3bfcf')
;

-- May 18, 2023, 2:04:40 PM CEST
INSERT INTO AD_Column (AD_Column_ID,Version,Name,AD_Table_ID,ColumnName,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,IsEncrypted,AD_Reference_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsAlwaysUpdateable,AD_Column_UU,IsToolbarButton) VALUES (215839,0.0,'RV_UnPosted_UU',635,'RV_UnPosted_UU',36,'N','N','N','N','N','N',10,0,0,'Y',TO_TIMESTAMP('2023-05-18 14:04:39','YYYY-MM-DD HH24:MI:SS'),100,TO_TIMESTAMP('2023-05-18 14:04:39','YYYY-MM-DD HH24:MI:SS'),100,203811,'N','N','D','N','4fd4f241-84d9-435c-a281-27d7d465ec04','N')
;

-- May 18, 2023, 2:04:53 PM CEST
INSERT INTO AD_Field (AD_Field_ID,Name,AD_Tab_ID,AD_Column_ID,IsDisplayed,DisplayLength,IsSameLine,IsHeading,IsFieldOnly,IsEncrypted,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,IsReadOnly,IsCentrallyMaintained,EntityType,AD_Field_UU,IsDisplayedGrid,ColumnSpan) VALUES (207625,'RV_UnPosted_UU',662,215839,'N',36,'N','N','N','N',0,0,'Y',TO_TIMESTAMP('2023-05-18 14:04:53','YYYY-MM-DD HH24:MI:SS'),100,TO_TIMESTAMP('2023-05-18 14:04:53','YYYY-MM-DD HH24:MI:SS'),100,'N','Y','D','0a8da8cb-8181-472f-9272-fbb8e18081e8','N',2)
;

