SET SQLBLANKLINES ON
SET DEFINE OFF

UPDATE a_asset_acct SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_acct MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_acct SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_acct MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_addition SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_addition MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_addition SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_addition MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_change SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_change MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_change SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_change MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_class SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_class MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_class SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_class MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_disposed SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_disposed MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_disposed SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_disposed MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_group_acct SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_group_acct MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_group_acct SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_group_acct MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_info_fin SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_info_fin MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_info_fin SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_info_fin MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_info_ins SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_info_ins MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_info_ins SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_info_ins MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_info_lic SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_info_lic MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_info_lic SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_info_lic MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_info_oth SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_info_oth MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_info_oth SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_info_oth MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_info_tax SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_info_tax MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_info_tax SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_info_tax MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_product SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_product MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_product SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_product MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_reval SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_reval MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_reval SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_reval MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_reval_entry SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_reval_entry MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_reval_entry SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_reval_entry MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_reval_index SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_reval_index MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_reval_index SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_reval_index MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_split SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_split MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_split SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_split MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_spread SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_spread MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_spread SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_spread MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_transfer SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_transfer MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_transfer SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_transfer MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_type SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_type MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_type SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_type MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_asset_use SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_asset_use MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_asset_use SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_asset_use MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_depreciation SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_depreciation MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_depreciation SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_depreciation MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_depreciation_build SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_depreciation_build MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE a_depreciation_build SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_depreciation_build MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE a_depreciation_convention SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_depreciation_convention MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_depreciation_convention SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_depreciation_convention MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_depreciation_entry SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_depreciation_entry MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_depreciation_entry SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_depreciation_entry MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_depreciation_exp SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_depreciation_exp MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_depreciation_exp SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_depreciation_exp MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_depreciation_forecast SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_depreciation_forecast MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_depreciation_forecast SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_depreciation_forecast MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_depreciation_method SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_depreciation_method MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_depreciation_method SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_depreciation_method MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_depreciation_table_detail SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_depreciation_table_detail MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_depreciation_table_detail SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_depreciation_table_detail MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_depreciation_table_header SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_depreciation_table_header MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_depreciation_table_header SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_depreciation_table_header MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_depreciation_workfile SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_depreciation_workfile MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_depreciation_workfile SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_depreciation_workfile MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_fundingmode SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_fundingmode MODIFY ( created DEFAULT SysDate ) ; 
UPDATE a_fundingmode SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_fundingmode MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_fundingmode_acct SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE a_fundingmode_acct MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE a_fundingmode_acct SET created=SysDate WHERE created IS NULL;
ALTER TABLE a_fundingmode_acct MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_chart SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_chart MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_chart SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_chart MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_chartdatasource SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_chartdatasource MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_chartdatasource SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_chartdatasource MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_ctxhelp SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_ctxhelp MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_ctxhelp SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_ctxhelp MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_ctxhelpmsg SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_ctxhelpmsg MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_ctxhelpmsg SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_ctxhelpmsg MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_element SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_element MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_housekeeping SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_housekeeping MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_housekeeping SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_housekeeping MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_indexcolumn SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_indexcolumn MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_indexcolumn SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_indexcolumn MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_infowindow_access SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_infowindow_access MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_infowindow_access SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_infowindow_access MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_migrationscript SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_migrationscript MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_migrationscript SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_migrationscript MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_modelvalidator SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_modelvalidator MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_modelvalidator SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_modelvalidator MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_package_imp_inst SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_package_imp_inst MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE ad_package_imp_inst SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_package_imp_inst MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE ad_package_uuid_map SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_package_uuid_map MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_package_uuid_map SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_package_uuid_map MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_passwordrule SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_passwordrule MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE ad_passwordrule SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_passwordrule MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE ad_pinstance SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_pinstance MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE ad_pinstance_para SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_pinstance_para MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE ad_pinstance_para SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_pinstance_para MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE ad_recentitem SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_recentitem MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_recentitem SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_recentitem MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_relationtype SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_relationtype MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_relationtype SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_relationtype MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_replicationdocument SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_replicationdocument MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_replicationdocument SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_replicationdocument MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_role_included SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_role_included MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_role_included SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_role_included MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_rule SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_rule MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_rule SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_rule MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_schedule SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_schedule MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_schedule SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_schedule MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_searchdefinition SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_searchdefinition MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE ad_searchdefinition SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_searchdefinition MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_storageprovider SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_storageprovider MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_storageprovider SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_storageprovider MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_sysconfig SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_sysconfig MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_sysconfig SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_sysconfig MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_tab_customization SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_tab_customization MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_tab_customization SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_tab_customization MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_table_scriptvalidator SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_table_scriptvalidator MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_table_scriptvalidator SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_table_scriptvalidator MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_tableindex SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_tableindex MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_tableindex SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_tableindex MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_toolbarbutton SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_toolbarbutton MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_toolbarbutton SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_toolbarbutton MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_toolbarbuttonrestrict SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_toolbarbuttonrestrict MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_toolbarbuttonrestrict SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_toolbarbuttonrestrict MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_viewcolumn SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_viewcolumn MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_viewcolumn SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_viewcolumn MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_viewcomponent SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_viewcomponent MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_viewcomponent SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_viewcomponent MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_wizardprocess SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_wizardprocess MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_wizardprocess SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_wizardprocess MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ad_zoomcondition SET created=SysDate WHERE created IS NULL;
ALTER TABLE ad_zoomcondition MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ad_zoomcondition SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ad_zoomcondition MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE asp_clientexception SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE asp_clientexception MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE asp_clientexception SET created=SysDate WHERE created IS NULL;
ALTER TABLE asp_clientexception MODIFY ( created DEFAULT SysDate ) ; 
UPDATE asp_clientlevel SET created=SysDate WHERE created IS NULL;
ALTER TABLE asp_clientlevel MODIFY ( created DEFAULT SysDate ) ; 
UPDATE asp_clientlevel SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE asp_clientlevel MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE asp_field SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE asp_field MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE asp_field SET created=SysDate WHERE created IS NULL;
ALTER TABLE asp_field MODIFY ( created DEFAULT SysDate ) ; 
UPDATE asp_form SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE asp_form MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE asp_form SET created=SysDate WHERE created IS NULL;
ALTER TABLE asp_form MODIFY ( created DEFAULT SysDate ) ; 
UPDATE asp_level SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE asp_level MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE asp_level SET created=SysDate WHERE created IS NULL;
ALTER TABLE asp_level MODIFY ( created DEFAULT SysDate ) ; 
UPDATE asp_module SET created=SysDate WHERE created IS NULL;
ALTER TABLE asp_module MODIFY ( created DEFAULT SysDate ) ; 
UPDATE asp_module SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE asp_module MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE asp_process SET created=SysDate WHERE created IS NULL;
ALTER TABLE asp_process MODIFY ( created DEFAULT SysDate ) ; 
UPDATE asp_process SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE asp_process MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE asp_process_para SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE asp_process_para MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE asp_process_para SET created=SysDate WHERE created IS NULL;
ALTER TABLE asp_process_para MODIFY ( created DEFAULT SysDate ) ; 
UPDATE asp_ref_list SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE asp_ref_list MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE asp_ref_list SET created=SysDate WHERE created IS NULL;
ALTER TABLE asp_ref_list MODIFY ( created DEFAULT SysDate ) ; 
UPDATE asp_tab SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE asp_tab MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE asp_tab SET created=SysDate WHERE created IS NULL;
ALTER TABLE asp_tab MODIFY ( created DEFAULT SysDate ) ; 
UPDATE asp_task SET created=SysDate WHERE created IS NULL;
ALTER TABLE asp_task MODIFY ( created DEFAULT SysDate ) ; 
UPDATE asp_task SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE asp_task MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE asp_window SET created=SysDate WHERE created IS NULL;
ALTER TABLE asp_window MODIFY ( created DEFAULT SysDate ) ; 
UPDATE asp_window SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE asp_window MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE asp_workflow SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE asp_workflow MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE asp_workflow SET created=SysDate WHERE created IS NULL;
ALTER TABLE asp_workflow MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_1099box SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_1099box MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_1099box SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_1099box MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_addresstransaction SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_addresstransaction MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_addresstransaction SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_addresstransaction MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_addressvalidation SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_addressvalidation MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_addressvalidation SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_addressvalidation MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_addressvalidationcfg SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_addressvalidationcfg MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_addressvalidationcfg SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_addressvalidationcfg MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_bankaccount_processor SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_bankaccount_processor MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_bankaccount_processor SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_bankaccount_processor MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_bp_shippingacct SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_bp_shippingacct MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_bp_shippingacct SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_bp_shippingacct MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_cashplan SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_cashplan MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_cashplan SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_cashplan MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_cashplanline SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_cashplanline MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_cashplanline SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_cashplanline MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_chargetype SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_chargetype MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_chargetype SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_chargetype MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_chargetype_doctype SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_chargetype_doctype MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_chargetype_doctype SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_chargetype_doctype MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_contactactivity SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_contactactivity MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_contactactivity SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_contactactivity MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_depositbatch SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_depositbatch MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_depositbatch SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_depositbatch MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_depositbatchline SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_depositbatchline MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_depositbatchline SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_depositbatchline MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_onlinetrxhistory SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_onlinetrxhistory MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_onlinetrxhistory SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_onlinetrxhistory MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_opportunity SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_opportunity MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_opportunity SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_opportunity MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_orderlandedcost SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_orderlandedcost MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_orderlandedcost SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_orderlandedcost MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_orderlandedcostallocation SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_orderlandedcostallocation MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_orderlandedcostallocation SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_orderlandedcostallocation MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_orderpayschedule SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_orderpayschedule MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_orderpayschedule SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_orderpayschedule MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_paymenttransaction SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_paymenttransaction MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_paymenttransaction SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_paymenttransaction MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_pospayment SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_pospayment MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_pospayment SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_pospayment MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_postendertype SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_postendertype MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_postendertype SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_postendertype MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_salesstage SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_salesstage MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_salesstage SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_salesstage MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_taxbase SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_taxbase MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_taxbase SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_taxbase MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_taxdefinition SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_taxdefinition MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_taxdefinition SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_taxdefinition MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_taxgroup SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_taxgroup MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_taxgroup SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_taxgroup MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_taxprovider SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_taxprovider MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_taxprovider SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_taxprovider MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_taxprovidercfg SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_taxprovidercfg MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_taxprovidercfg SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_taxprovidercfg MODIFY ( created DEFAULT SysDate ) ; 
UPDATE c_taxtype SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE c_taxtype MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE c_taxtype SET created=SysDate WHERE created IS NULL;
ALTER TABLE c_taxtype MODIFY ( created DEFAULT SysDate ) ; 
UPDATE dd_networkdistribution SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE dd_networkdistribution MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE dd_networkdistribution SET created=SysDate WHERE created IS NULL;
ALTER TABLE dd_networkdistribution MODIFY ( created DEFAULT SysDate ) ; 
UPDATE dd_networkdistributionline SET created=SysDate WHERE created IS NULL;
ALTER TABLE dd_networkdistributionline MODIFY ( created DEFAULT SysDate ) ; 
UPDATE dd_networkdistributionline SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE dd_networkdistributionline MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE dd_order SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE dd_order MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE dd_order SET created=SysDate WHERE created IS NULL;
ALTER TABLE dd_order MODIFY ( created DEFAULT SysDate ) ; 
UPDATE dd_orderline SET created=SysDate WHERE created IS NULL;
ALTER TABLE dd_orderline MODIFY ( created DEFAULT SysDate ) ; 
UPDATE dd_orderline SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE dd_orderline MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE exp_format SET created=SysDate WHERE created IS NULL;
ALTER TABLE exp_format MODIFY ( created DEFAULT SysDate ) ; 
UPDATE exp_format SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE exp_format MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE exp_formatline SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE exp_formatline MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE exp_formatline SET created=SysDate WHERE created IS NULL;
ALTER TABLE exp_formatline MODIFY ( created DEFAULT SysDate ) ; 
UPDATE exp_processor SET created=SysDate WHERE created IS NULL;
ALTER TABLE exp_processor MODIFY ( created DEFAULT SysDate ) ; 
UPDATE exp_processor SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE exp_processor MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE exp_processor_type SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE exp_processor_type MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE exp_processor_type SET created=SysDate WHERE created IS NULL;
ALTER TABLE exp_processor_type MODIFY ( created DEFAULT SysDate ) ; 
UPDATE exp_processorparameter SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE exp_processorparameter MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE exp_processorparameter SET created=SysDate WHERE created IS NULL;
ALTER TABLE exp_processorparameter MODIFY ( created DEFAULT SysDate ) ; 
UPDATE fact_acct_summary SET created=SysDate WHERE created IS NULL;
ALTER TABLE fact_acct_summary MODIFY ( created DEFAULT SysDate ) ; 
UPDATE fact_acct_summary SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE fact_acct_summary MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE fact_reconciliation SET created=SysDate WHERE created IS NULL;
ALTER TABLE fact_reconciliation MODIFY ( created DEFAULT SysDate ) ; 
UPDATE fact_reconciliation SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE fact_reconciliation MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE gl_journalgenerator SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE gl_journalgenerator MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE gl_journalgenerator SET created=SysDate WHERE created IS NULL;
ALTER TABLE gl_journalgenerator MODIFY ( created DEFAULT SysDate ) ; 
UPDATE gl_journalgeneratorline SET created=SysDate WHERE created IS NULL;
ALTER TABLE gl_journalgeneratorline MODIFY ( created DEFAULT SysDate ) ; 
UPDATE gl_journalgeneratorline SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE gl_journalgeneratorline MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE gl_journalgeneratorsource SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE gl_journalgeneratorsource MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE gl_journalgeneratorsource SET created=SysDate WHERE created IS NULL;
ALTER TABLE gl_journalgeneratorsource MODIFY ( created DEFAULT SysDate ) ; 
UPDATE hr_attribute SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE hr_attribute MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE hr_attribute SET created=SysDate WHERE created IS NULL;
ALTER TABLE hr_attribute MODIFY ( created DEFAULT SysDate ) ; 
UPDATE hr_concept SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE hr_concept MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE hr_concept SET created=SysDate WHERE created IS NULL;
ALTER TABLE hr_concept MODIFY ( created DEFAULT SysDate ) ; 
UPDATE hr_concept_acct SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE hr_concept_acct MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE hr_concept_acct SET created=SysDate WHERE created IS NULL;
ALTER TABLE hr_concept_acct MODIFY ( created DEFAULT SysDate ) ; 
UPDATE hr_concept_category SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE hr_concept_category MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE hr_concept_category SET created=SysDate WHERE created IS NULL;
ALTER TABLE hr_concept_category MODIFY ( created DEFAULT SysDate ) ; 
UPDATE hr_contract SET created=SysDate WHERE created IS NULL;
ALTER TABLE hr_contract MODIFY ( created DEFAULT SysDate ) ; 
UPDATE hr_contract SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE hr_contract MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE hr_department SET created=SysDate WHERE created IS NULL;
ALTER TABLE hr_department MODIFY ( created DEFAULT SysDate ) ; 
UPDATE hr_department SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE hr_department MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE hr_employee SET created=SysDate WHERE created IS NULL;
ALTER TABLE hr_employee MODIFY ( created DEFAULT SysDate ) ; 
UPDATE hr_employee SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE hr_employee MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE hr_job SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE hr_job MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE hr_job SET created=SysDate WHERE created IS NULL;
ALTER TABLE hr_job MODIFY ( created DEFAULT SysDate ) ; 
UPDATE hr_list SET created=SysDate WHERE created IS NULL;
ALTER TABLE hr_list MODIFY ( created DEFAULT SysDate ) ; 
UPDATE hr_list SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE hr_list MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE hr_listline SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE hr_listline MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE hr_listline SET created=SysDate WHERE created IS NULL;
ALTER TABLE hr_listline MODIFY ( created DEFAULT SysDate ) ; 
UPDATE hr_listtype SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE hr_listtype MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE hr_listtype SET created=SysDate WHERE created IS NULL;
ALTER TABLE hr_listtype MODIFY ( created DEFAULT SysDate ) ; 
UPDATE hr_listversion SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE hr_listversion MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE hr_listversion SET created=SysDate WHERE created IS NULL;
ALTER TABLE hr_listversion MODIFY ( created DEFAULT SysDate ) ; 
UPDATE hr_movement SET created=SysDate WHERE created IS NULL;
ALTER TABLE hr_movement MODIFY ( created DEFAULT SysDate ) ; 
UPDATE hr_movement SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE hr_movement MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE hr_payroll SET created=SysDate WHERE created IS NULL;
ALTER TABLE hr_payroll MODIFY ( created DEFAULT SysDate ) ; 
UPDATE hr_payroll SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE hr_payroll MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE hr_payrollconcept SET created=SysDate WHERE created IS NULL;
ALTER TABLE hr_payrollconcept MODIFY ( created DEFAULT SysDate ) ; 
UPDATE hr_payrollconcept SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE hr_payrollconcept MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE hr_period SET created=SysDate WHERE created IS NULL;
ALTER TABLE hr_period MODIFY ( created DEFAULT SysDate ) ; 
UPDATE hr_period SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE hr_period MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE hr_process SET created=SysDate WHERE created IS NULL;
ALTER TABLE hr_process MODIFY ( created DEFAULT SysDate ) ; 
UPDATE hr_process SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE hr_process MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE hr_year SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE hr_year MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE hr_year SET created=SysDate WHERE created IS NULL;
ALTER TABLE hr_year MODIFY ( created DEFAULT SysDate ) ; 
UPDATE i_asset SET created=SysDate WHERE created IS NULL;
ALTER TABLE i_asset MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE i_asset SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE i_asset MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE i_bankstatement SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE i_bankstatement MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE i_bankstatement SET created=SysDate WHERE created IS NULL;
ALTER TABLE i_bankstatement MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE i_bpartner SET created=SysDate WHERE created IS NULL;
ALTER TABLE i_bpartner MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE i_bpartner SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE i_bpartner MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE i_conversion_rate SET created=SysDate WHERE created IS NULL;
ALTER TABLE i_conversion_rate MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE i_conversion_rate SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE i_conversion_rate MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE i_elementvalue SET created=SysDate WHERE created IS NULL;
ALTER TABLE i_elementvalue MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE i_elementvalue SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE i_elementvalue MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE i_fajournal SET created=SysDate WHERE created IS NULL;
ALTER TABLE i_fajournal MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE i_fajournal SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE i_fajournal MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE i_fixedasset SET created=SysDate WHERE created IS NULL;
ALTER TABLE i_fixedasset MODIFY ( created DEFAULT SysDate ) ; 
UPDATE i_fixedasset SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE i_fixedasset MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE i_gljournal SET created=SysDate WHERE created IS NULL;
ALTER TABLE i_gljournal MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE i_gljournal SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE i_gljournal MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE i_hr_movement SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE i_hr_movement MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE i_hr_movement SET created=SysDate WHERE created IS NULL;
ALTER TABLE i_hr_movement MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE i_inventory SET created=SysDate WHERE created IS NULL;
ALTER TABLE i_inventory MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE i_inventory SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE i_inventory MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE i_invoice SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE i_invoice MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE i_invoice SET created=SysDate WHERE created IS NULL;
ALTER TABLE i_invoice MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE i_movement SET created=SysDate WHERE created IS NULL;
ALTER TABLE i_movement MODIFY ( created DEFAULT SysDate ) ; 
UPDATE i_movement SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE i_movement MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE i_order SET created=SysDate WHERE created IS NULL;
ALTER TABLE i_order MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE i_order SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE i_order MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE i_payment SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE i_payment MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE i_payment SET created=SysDate WHERE created IS NULL;
ALTER TABLE i_payment MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE i_pricelist SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE i_pricelist MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE i_pricelist SET created=SysDate WHERE created IS NULL;
ALTER TABLE i_pricelist MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE i_product SET created=SysDate WHERE created IS NULL;
ALTER TABLE i_product MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE i_product SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE i_product MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE i_productplanning SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE i_productplanning MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE i_productplanning SET created=SysDate WHERE created IS NULL;
ALTER TABLE i_productplanning MODIFY ( created DEFAULT SysDate ) ; 
UPDATE i_reportline SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE i_reportline MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE i_reportline SET created=SysDate WHERE created IS NULL;
ALTER TABLE i_reportline MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE imp_processor SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE imp_processor MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE imp_processor SET created=SysDate WHERE created IS NULL;
ALTER TABLE imp_processor MODIFY ( created DEFAULT SysDate ) ; 
UPDATE imp_processor_type SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE imp_processor_type MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE imp_processor_type SET created=SysDate WHERE created IS NULL;
ALTER TABLE imp_processor_type MODIFY ( created DEFAULT SysDate ) ; 
UPDATE imp_processorlog SET created=SysDate WHERE created IS NULL;
ALTER TABLE imp_processorlog MODIFY ( created DEFAULT SysDate ) ; 
UPDATE imp_processorlog SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE imp_processorlog MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE imp_processorparameter SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE imp_processorparameter MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE imp_processorparameter SET created=SysDate WHERE created IS NULL;
ALTER TABLE imp_processorparameter MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_bp_price SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_bp_price MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_bp_price SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_bp_price MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_commodityshipment SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_commodityshipment MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_commodityshipment SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_commodityshipment MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_costhistory SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_costhistory MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_costhistory SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_costhistory MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_packagemps SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_packagemps MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_packagemps SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_packagemps MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_parttype SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_parttype MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_parttype SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_parttype MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_product_qualitytest SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_product_qualitytest MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_product_qualitytest SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_product_qualitytest MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_productpricevendorbreak SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_productpricevendorbreak MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_productpricevendorbreak SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_productpricevendorbreak MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_promotion SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_promotion MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_promotion SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_promotion MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_promotiondistribution SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_promotiondistribution MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_promotiondistribution SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_promotiondistribution MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_promotiongroup SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_promotiongroup MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_promotiongroup SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_promotiongroup MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_promotiongroupline SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_promotiongroupline MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_promotiongroupline SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_promotiongroupline MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_promotionline SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_promotionline MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_promotionline SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_promotionline MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_promotionprecondition SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_promotionprecondition MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_promotionprecondition SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_promotionprecondition MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_promotionreward SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_promotionreward MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_promotionreward SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_promotionreward MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_qualitytest SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_qualitytest MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_qualitytest SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_qualitytest MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_qualitytestresult SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_qualitytestresult MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_qualitytestresult SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_qualitytestresult MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_rmatax SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_rmatax MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_rmatax SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_rmatax MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_shippercfg SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_shippercfg MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_shippercfg SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_shippercfg MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_shipperlabels SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_shipperlabels MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_shipperlabels SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_shipperlabels MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_shipperlabelscfg SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_shipperlabelscfg MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_shipperlabelscfg SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_shipperlabelscfg MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_shipperpackaging SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_shipperpackaging MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_shipperpackaging SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_shipperpackaging MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_shipperpackagingcfg SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_shipperpackagingcfg MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_shipperpackagingcfg SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_shipperpackagingcfg MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_shipperpickuptypes SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_shipperpickuptypes MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_shipperpickuptypes SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_shipperpickuptypes MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_shipperpickuptypescfg SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_shipperpickuptypescfg MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_shipperpickuptypescfg SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_shipperpickuptypescfg MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_shippingprocessor SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_shippingprocessor MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_shippingprocessor SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_shippingprocessor MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_shippingprocessorcfg SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_shippingprocessorcfg MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_shippingprocessorcfg SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_shippingprocessorcfg MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_shippingtransaction SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_shippingtransaction MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_shippingtransaction SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_shippingtransaction MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_shippingtransactionline SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_shippingtransactionline MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_shippingtransactionline SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_shippingtransactionline MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_storageonhand SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_storageonhand MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_storageonhand SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_storageonhand MODIFY ( created DEFAULT SysDate ) ; 
UPDATE m_storagereservation SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE m_storagereservation MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE m_storagereservation SET created=SysDate WHERE created IS NULL;
ALTER TABLE m_storagereservation MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pa_dashboardcontent SET created=SysDate WHERE created IS NULL;
ALTER TABLE pa_dashboardcontent MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pa_dashboardcontent SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pa_dashboardcontent MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE pa_dashboardcontent_access SET created=SysDate WHERE created IS NULL;
ALTER TABLE pa_dashboardcontent_access MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE pa_dashboardcontent_access SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pa_dashboardcontent_access MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE pa_dashboardpreference SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pa_dashboardpreference MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE pa_dashboardpreference SET created=SysDate WHERE created IS NULL;
ALTER TABLE pa_dashboardpreference MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pa_reportcube SET created=SysDate WHERE created IS NULL;
ALTER TABLE pa_reportcube MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pa_reportcube SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pa_reportcube MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE pp_cost_collector SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pp_cost_collector MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE pp_cost_collector SET created=SysDate WHERE created IS NULL;
ALTER TABLE pp_cost_collector MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pp_cost_collectorma SET created=SysDate WHERE created IS NULL;
ALTER TABLE pp_cost_collectorma MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pp_cost_collectorma SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pp_cost_collectorma MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE pp_mrp SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pp_mrp MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE pp_mrp SET created=SysDate WHERE created IS NULL;
ALTER TABLE pp_mrp MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pp_order SET created=SysDate WHERE created IS NULL;
ALTER TABLE pp_order MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pp_order SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pp_order MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE pp_order_bom SET created=SysDate WHERE created IS NULL;
ALTER TABLE pp_order_bom MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pp_order_bom SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pp_order_bom MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE pp_order_bomline SET created=SysDate WHERE created IS NULL;
ALTER TABLE pp_order_bomline MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pp_order_bomline SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pp_order_bomline MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE pp_order_cost SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pp_order_cost MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE pp_order_cost SET created=SysDate WHERE created IS NULL;
ALTER TABLE pp_order_cost MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pp_order_node SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pp_order_node MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE pp_order_node SET created=SysDate WHERE created IS NULL;
ALTER TABLE pp_order_node MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pp_order_node_asset SET created=SysDate WHERE created IS NULL;
ALTER TABLE pp_order_node_asset MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pp_order_node_asset SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pp_order_node_asset MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE pp_order_node_product SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pp_order_node_product MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE pp_order_node_product SET created=SysDate WHERE created IS NULL;
ALTER TABLE pp_order_node_product MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pp_order_nodenext SET created=SysDate WHERE created IS NULL;
ALTER TABLE pp_order_nodenext MODIFY ( created DEFAULT SysDate NOT NULL ) ; 
UPDATE pp_order_nodenext SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pp_order_nodenext MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE pp_order_workflow SET created=SysDate WHERE created IS NULL;
ALTER TABLE pp_order_workflow MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pp_order_workflow SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pp_order_workflow MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE pp_product_bom SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pp_product_bom MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE pp_product_bom SET created=SysDate WHERE created IS NULL;
ALTER TABLE pp_product_bom MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pp_product_bomline SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pp_product_bomline MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE pp_product_bomline SET created=SysDate WHERE created IS NULL;
ALTER TABLE pp_product_bomline MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pp_product_planning SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pp_product_planning MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE pp_product_planning SET created=SysDate WHERE created IS NULL;
ALTER TABLE pp_product_planning MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pp_wf_node_asset SET created=SysDate WHERE created IS NULL;
ALTER TABLE pp_wf_node_asset MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pp_wf_node_asset SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pp_wf_node_asset MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE pp_wf_node_product SET created=SysDate WHERE created IS NULL;
ALTER TABLE pp_wf_node_product MODIFY ( created DEFAULT SysDate ) ; 
UPDATE pp_wf_node_product SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE pp_wf_node_product MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE qm_specification SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE qm_specification MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE qm_specification SET created=SysDate WHERE created IS NULL;
ALTER TABLE qm_specification MODIFY ( created DEFAULT SysDate ) ; 
UPDATE qm_specificationline SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE qm_specificationline MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE qm_specificationline SET created=SysDate WHERE created IS NULL;
ALTER TABLE qm_specificationline MODIFY ( created DEFAULT SysDate ) ; 
UPDATE t_1099extract SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE t_1099extract MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE t_1099extract SET created=SysDate WHERE created IS NULL;
ALTER TABLE t_1099extract MODIFY ( created DEFAULT SysDate ) ; 
UPDATE t_bom_indented SET created=SysDate WHERE created IS NULL;
ALTER TABLE t_bom_indented MODIFY ( created DEFAULT SysDate ) ; 
UPDATE t_bom_indented SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE t_bom_indented MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE t_bomline SET created=SysDate WHERE created IS NULL;
ALTER TABLE t_bomline MODIFY ( created DEFAULT SysDate ) ; 
UPDATE t_bomline SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE t_bomline MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE t_cashflow SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE t_cashflow MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE t_cashflow SET created=SysDate WHERE created IS NULL;
ALTER TABLE t_cashflow MODIFY ( created DEFAULT SysDate ) ; 
UPDATE t_mrp_crp SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE t_mrp_crp MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE t_mrp_crp SET created=SysDate WHERE created IS NULL;
ALTER TABLE t_mrp_crp MODIFY ( created DEFAULT SysDate ) ; 
UPDATE t_reconciliation SET created=SysDate WHERE created IS NULL;
ALTER TABLE t_reconciliation MODIFY ( created DEFAULT SysDate ) ; 
UPDATE t_reconciliation SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE t_reconciliation MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE t_replenish SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE t_replenish MODIFY ( updated DEFAULT SysDate NOT NULL ) ; 
UPDATE t_trialbalance SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE t_trialbalance MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE t_trialbalance SET created=SysDate WHERE created IS NULL;
ALTER TABLE t_trialbalance MODIFY ( created DEFAULT SysDate ) ; 
UPDATE u_posterminal SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE u_posterminal MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE u_posterminal SET created=SysDate WHERE created IS NULL;
ALTER TABLE u_posterminal MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ws_webservice SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ws_webservice MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ws_webservice SET created=SysDate WHERE created IS NULL;
ALTER TABLE ws_webservice MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ws_webservice_para SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ws_webservice_para MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ws_webservice_para SET created=SysDate WHERE created IS NULL;
ALTER TABLE ws_webservice_para MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ws_webservicefieldinput SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ws_webservicefieldinput MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ws_webservicefieldinput SET created=SysDate WHERE created IS NULL;
ALTER TABLE ws_webservicefieldinput MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ws_webservicefieldoutput SET created=SysDate WHERE created IS NULL;
ALTER TABLE ws_webservicefieldoutput MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ws_webservicefieldoutput SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ws_webservicefieldoutput MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ws_webservicemethod SET created=SysDate WHERE created IS NULL;
ALTER TABLE ws_webservicemethod MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ws_webservicemethod SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ws_webservicemethod MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ws_webservicetype SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ws_webservicetype MODIFY ( updated DEFAULT SysDate ) ; 
UPDATE ws_webservicetype SET created=SysDate WHERE created IS NULL;
ALTER TABLE ws_webservicetype MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ws_webservicetypeaccess SET created=SysDate WHERE created IS NULL;
ALTER TABLE ws_webservicetypeaccess MODIFY ( created DEFAULT SysDate ) ; 
UPDATE ws_webservicetypeaccess SET updated=SysDate WHERE updated IS NULL;
ALTER TABLE ws_webservicetypeaccess MODIFY ( updated DEFAULT SysDate ) ; 

UPDATE AD_Column SET DefaultValue='SYSDATE' WHERE DefaultValue is null AND ColumnName='Created';

UPDATE AD_Column SET DefaultValue='SYSDATE' WHERE DefaultValue is null AND ColumnName='Updated';

UPDATE AD_Column SET IsMandatory='Y' WHERE IsMandatory='N' AND ColumnName='Created';

UPDATE AD_Column SET IsMandatory='Y' WHERE IsMandatory='N' AND ColumnName='Updated';

SELECT register_migration_script('201404171500_IDEMPIERE-709.sql') FROM dual
;
