-- IDEMPIERE-6768 Missing columns in database view
SELECT register_migration_script('202603082215_IDEMPIERE-6768.sql') FROM dual;

SET SQLBLANKLINES ON
SET DEFINE OFF

-- Mar 8, 2026, 10:21:29 PM CET
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217753,'019ccf53-9f50-7f2e-b7c9-4fbf09f21b16',TO_TIMESTAMP('2026-03-08 22:21:29','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2026-03-08 22:21:29','YYYY-MM-DD HH24:MI:SS'),100,200213,'c_charge_id','f.c_charge_id',1930)
;

-- Mar 8, 2026, 10:21:39 PM CET
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217754,'019ccf53-c38c-7d15-ac66-e1f5448c2da9',TO_TIMESTAMP('2026-03-08 22:21:38','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2026-03-08 22:21:38','YYYY-MM-DD HH24:MI:SS'),100,200213,'c_costcenter_id','f.c_costcenter_id',1940)
;

-- Mar 8, 2026, 10:21:45 PM CET
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217755,'019ccf53-db79-7ddc-86e9-d38153450968',TO_TIMESTAMP('2026-03-08 22:21:45','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2026-03-08 22:21:45','YYYY-MM-DD HH24:MI:SS'),100,200213,'c_department_id','f.c_department_id',1950)
;

-- Mar 8, 2026, 10:21:50 PM CET
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217756,'019ccf53-f14e-7729-b181-75e9cc495638',TO_TIMESTAMP('2026-03-08 22:21:50','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2026-03-08 22:21:50','YYYY-MM-DD HH24:MI:SS'),100,200213,'c_employee_id','f.c_employee_id',1960)
;

-- Mar 8, 2026, 10:21:56 PM CET
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217757,'019ccf54-07f8-7f8a-ba61-32db63eddb6c',TO_TIMESTAMP('2026-03-08 22:21:56','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2026-03-08 22:21:56','YYYY-MM-DD HH24:MI:SS'),100,200213,'customfieldtext1','f.customfieldtext1',1970)
;

-- Mar 8, 2026, 10:22:01 PM CET
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217758,'019ccf54-1b9f-71f4-9213-5c5130339ef2',TO_TIMESTAMP('2026-03-08 22:22:01','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2026-03-08 22:22:01','YYYY-MM-DD HH24:MI:SS'),100,200213,'customfieldtext2','f.customfieldtext2',1980)
;

-- Mar 8, 2026, 10:22:07 PM CET
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217759,'019ccf54-3210-76f8-b3fa-26fd985298e2',TO_TIMESTAMP('2026-03-08 22:22:07','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2026-03-08 22:22:07','YYYY-MM-DD HH24:MI:SS'),100,200213,'customfieldtext3','f.customfieldtext3',1990)
;

-- Mar 8, 2026, 10:22:12 PM CET
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217760,'019ccf54-462c-739a-856f-75785fbf3070',TO_TIMESTAMP('2026-03-08 22:22:12','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2026-03-08 22:22:12','YYYY-MM-DD HH24:MI:SS'),100,200213,'customfieldtext4','f.customfieldtext4',2000)
;

-- Mar 8, 2026, 10:22:17 PM CET
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217761,'019ccf54-59aa-71f1-a1db-02224ab134be',TO_TIMESTAMP('2026-03-08 22:22:17','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2026-03-08 22:22:17','YYYY-MM-DD HH24:MI:SS'),100,200213,'m_attributesetinstance_id','f.m_attributesetinstance_id',2010)
;

-- Mar 8, 2026, 10:22:23 PM CET
INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0,217762,'019ccf54-6ee1-77d9-8c69-c87dc9c5764f',TO_TIMESTAMP('2026-03-08 22:22:22','YYYY-MM-DD HH24:MI:SS'),100,'D','Y',TO_TIMESTAMP('2026-03-08 22:22:22','YYYY-MM-DD HH24:MI:SS'),100,200213,'m_warehouse_id','f.m_warehouse_id',2020)
;

-- Mar 8, 2026, 10:22:33 PM CET
CREATE OR REPLACE VIEW T_RV_Reconciliation(AD_Client_ID, AD_Org_ID, IsActive, Created, CreatedBy, Updated, UpdatedBy, Fact_Acct_ID, C_AcctSchema_ID, Account_ID, DateTrx, DateAcct, C_Period_ID, AD_Table_ID, Record_ID, Line_ID, GL_Category_ID, GL_Budget_ID, C_Tax_ID, M_Locator_ID, PostingType, C_Currency_ID, AmtSourceDr, AmtSourceCr, AmtSource, AmtAcctDr, AmtAcctCr, AmtAcct, Rate, C_UOM_ID, Qty, M_Product_ID, C_BPartner_ID, AD_OrgTrx_ID, C_LocFrom_ID, C_LocTo_ID, C_SalesRegion_ID, C_Project_ID, C_Campaign_ID, C_Activity_ID, User1_ID, User2_ID, A_Asset_ID, Description, OrgValue, OrgName, AccountValue, Name, AccountType, BPartnerValue, BPName, C_BP_Group_ID, ProductValue, ProductName, UPC, M_Product_Category_ID, C_ProjectPhase_ID, C_ProjectTask_ID, C_SubAcct_ID, UserElement1_ID, UserElement2_ID, ad_org_description, ad_org_isactive, C_ElementValue_AD_Org_ID, C_BankAccount_ID, C_ElementValue_C_Currency_ID, C_Element_ID, C_ElementValue_ID, c_elementvalue_description, c_elementvalue_isactive, IsBankAccount, IsForeignCurrency, c_elementvalue_issummary, c_bp_acqusitioncost, c_bp_actuallifetimevalue, c_bp_ad_language, C_BP_AD_OrgBP_ID, C_BP_AD_Org_ID, C_BP_BPartner_Parent_ID, C_BP_C_Dunning_ID, C_BP_C_Greeting_ID, C_BP_C_InvoiceSchedule_ID, C_BP_C_PaymentTerm_ID, c_bp_created, C_BP_CreatedBy, C_BP_C_TaxGroup_ID, c_bp_deliveryrule, c_bp_deliveryviarule, c_bp_description, c_bp_dunninggrace, DUNS, c_bp_firstsale, c_bp_flatdiscount, c_bp_freightcostrule, c_bp_invoicerule, c_bp_isactive, c_bp_iscustomer, c_bp_isdiscountprinted, c_bp_isemployee, c_bp_ismanufacturer, c_bp_isonetime, c_bp_ispotaxexempt, c_bp_isprospect, c_bp_issalesrep, c_bp_issummary, c_bp_istaxexempt, c_bp_isvendor, C_BP_Logo_ID, C_BP_M_DiscountSchema_ID, C_BP_M_PriceList_ID, NAICS, c_bp_name2, c_bp_numberemployees, c_bp_paymentrule, c_bp_paymentrulepo, C_BP_PO_DiscountSchema_ID, C_BP_PO_PaymentTerm_ID, C_BP_PO_PriceList_ID, c_bp_poreference, c_bp_potentiallifetimevalue, c_bp_rating, ReferenceNo, C_BP_SalesRep_ID, c_bp_salesvolume, c_bp_sendemail, c_bp_shareofcustomer, c_bp_shelflifeminpct, c_bp_so_creditlimit, c_bp_socreditstatus, c_bp_so_creditused, c_bp_so_description, TaxID, c_bp_totalopenbalance, c_bp_updated, C_BP_UpdatedBy, c_bp_url, M_Product_AD_Org_ID, Classification, m_product_copyfrom, m_product_created, M_Product_CreatedBy, C_RevenueRecognition_ID, C_SubscriptionType_ID, C_TaxCategory_ID, M_Product_C_UOM_ID, m_product_description, DescriptionURL, Discontinued, DiscontinuedAt,
DocumentNote, Group1, Group2, GuaranteeDays, GuaranteeDaysMin, Help, ImageURL, m_product_isactive, IsDropShip, IsExcludeAutoDelivery, IsInvoicePrintDetails, IsPickListPrintDetails, IsPurchased, IsSelfService, IsSold, IsStocked, m_product_issummary, IsVerified, IsWebStoreFeatured, LowLevel, M_Product_M_AttributeSet_ID, M_Product_M_ASI_ID, M_FreightCategory_ID, M_Product_M_Locator_ID, m_product_processing, ProductType, R_MailText_ID, M_Product_SalesRep_ID, S_ExpenseType_ID, ShelfDepth, ShelfHeight, ShelfWidth, SKU, S_Resource_ID, UnitsPerPack, UnitsPerPallet, m_product_updated, M_Product_UpdatedBy, VersionNo, Volume, Weight, AD_PInstance_ID, MatchCode, c_charge_id, c_costcenter_id, c_department_id, c_employee_id, customfieldtext1, customfieldtext2, customfieldtext3, customfieldtext4, m_attributesetinstance_id, m_warehouse_id) AS SELECT f.ad_client_id AS AD_Client_ID, f.ad_org_id AS AD_Org_ID, f.isactive AS IsActive, f.created AS Created, f.createdby AS CreatedBy, f.updated AS Updated, f.updatedby AS UpdatedBy, f.fact_acct_id AS Fact_Acct_ID, f.c_acctschema_id AS C_AcctSchema_ID, f.account_id AS Account_ID, f.datetrx AS DateTrx, f.dateacct AS DateAcct, f.c_period_id AS C_Period_ID, f.ad_table_id AS AD_Table_ID, f.record_id AS Record_ID, f.line_id AS Line_ID, f.gl_category_id AS GL_Category_ID, f.gl_budget_id AS GL_Budget_ID, f.c_tax_id AS C_Tax_ID, f.m_locator_id AS M_Locator_ID, f.postingtype AS PostingType, f.c_currency_id AS C_Currency_ID, f.amtsourcedr AS AmtSourceDr, f.amtsourcecr AS AmtSourceCr, f.amtsource AS AmtSource, f.amtacctdr AS AmtAcctDr, f.amtacctcr AS AmtAcctCr, f.amtacct AS AmtAcct, f.rate AS Rate, f.c_uom_id AS C_UOM_ID, f.qty AS Qty, f.m_product_id AS M_Product_ID, f.c_bpartner_id AS C_BPartner_ID, f.ad_orgtrx_id AS AD_OrgTrx_ID, f.c_locfrom_id AS C_LocFrom_ID, f.c_locto_id AS C_LocTo_ID, f.c_salesregion_id AS C_SalesRegion_ID, f.c_project_id AS C_Project_ID, f.c_campaign_id AS C_Campaign_ID, f.c_activity_id AS C_Activity_ID, f.user1_id AS User1_ID, f.user2_id AS User2_ID, f.a_asset_id AS A_Asset_ID, f.description AS Description, f.orgvalue AS OrgValue, f.orgname AS OrgName, f.accountvalue AS AccountValue, f.name AS Name, f.accounttype AS AccountType, f.bpartnervalue AS BPartnerValue, f.bpname AS BPName, f.c_bp_group_id AS C_BP_Group_ID, f.productvalue AS ProductValue, f.productname AS ProductName, f.upc AS UPC, f.m_product_category_id AS M_Product_Category_ID, f.c_projectphase_id AS C_ProjectPhase_ID,
f.c_projecttask_id AS C_ProjectTask_ID, f.c_subacct_id AS C_SubAcct_ID, f.userelement1_id AS UserElement1_ID, f.userelement2_id AS UserElement2_ID, f.ad_org_description AS ad_org_description, f.ad_org_isactive AS ad_org_isactive, f.c_elementvalue_ad_org_id AS C_ElementValue_AD_Org_ID, f.c_bankaccount_id AS C_BankAccount_ID, f.c_elementvalue_c_currency_id AS C_ElementValue_C_Currency_ID, f.c_element_id AS C_Element_ID, f.c_elementvalue_id AS C_ElementValue_ID, f.c_elementvalue_description AS c_elementvalue_description, f.c_elementvalue_isactive AS c_elementvalue_isactive, f.isbankaccount AS IsBankAccount, f.isforeigncurrency AS IsForeignCurrency, f.c_elementvalue_issummary AS c_elementvalue_issummary, f.c_bp_acqusitioncost AS c_bp_acqusitioncost, f.c_bp_actuallifetimevalue AS c_bp_actuallifetimevalue, f.c_bp_ad_language AS c_bp_ad_language, f.c_bp_ad_orgbp_id AS C_BP_AD_OrgBP_ID, f.c_bp_ad_org_id AS C_BP_AD_Org_ID, f.c_bp_bpartner_parent_id AS C_BP_BPartner_Parent_ID, f.c_bp_c_dunning_id AS C_BP_C_Dunning_ID, f.c_bp_c_greeting_id AS C_BP_C_Greeting_ID, f.c_bp_c_invoiceschedule_id AS C_BP_C_InvoiceSchedule_ID, f.c_bp_c_paymentterm_id AS C_BP_C_PaymentTerm_ID, f.c_bp_created AS c_bp_created, f.c_bp_createdby AS C_BP_CreatedBy, f.c_bp_c_taxgroup_id AS C_BP_C_TaxGroup_ID, f.c_bp_deliveryrule AS c_bp_deliveryrule, f.c_bp_deliveryviarule AS c_bp_deliveryviarule, f.c_bp_description AS c_bp_description, f.c_bp_dunninggrace AS c_bp_dunninggrace, f.duns AS DUNS, f.c_bp_firstsale AS c_bp_firstsale, f.c_bp_flatdiscount AS c_bp_flatdiscount, f.c_bp_freightcostrule AS c_bp_freightcostrule, f.c_bp_invoicerule AS c_bp_invoicerule, f.c_bp_isactive AS c_bp_isactive, f.c_bp_iscustomer AS c_bp_iscustomer, f.c_bp_isdiscountprinted AS c_bp_isdiscountprinted, f.c_bp_isemployee AS c_bp_isemployee, f.c_bp_ismanufacturer AS c_bp_ismanufacturer, f.c_bp_isonetime AS c_bp_isonetime, f.c_bp_ispotaxexempt AS c_bp_ispotaxexempt, f.c_bp_isprospect AS c_bp_isprospect, f.c_bp_issalesrep AS c_bp_issalesrep, f.c_bp_issummary AS c_bp_issummary, f.c_bp_istaxexempt AS c_bp_istaxexempt, f.c_bp_isvendor AS c_bp_isvendor, f.c_bp_logo_id AS C_BP_Logo_ID, f.c_bp_m_discountschema_id AS C_BP_M_DiscountSchema_ID, f.c_bp_m_pricelist_id AS C_BP_M_PriceList_ID, f.naics AS NAICS, f.c_bp_name2 AS c_bp_name2, f.c_bp_numberemployees AS c_bp_numberemployees, f.c_bp_paymentrule AS c_bp_paymentrule, f.c_bp_paymentrulepo AS c_bp_paymentrulepo, f.c_bp_po_discountschema_id AS C_BP_PO_DiscountSchema_ID,
f.c_bp_po_paymentterm_id AS C_BP_PO_PaymentTerm_ID, f.c_bp_po_pricelist_id AS C_BP_PO_PriceList_ID, f.c_bp_poreference AS c_bp_poreference, f.c_bp_potentiallifetimevalue AS c_bp_potentiallifetimevalue, f.c_bp_rating AS c_bp_rating, f.referenceno AS ReferenceNo, f.c_bp_salesrep_id AS C_BP_SalesRep_ID, f.c_bp_salesvolume AS c_bp_salesvolume, f.c_bp_sendemail AS c_bp_sendemail, f.c_bp_shareofcustomer AS c_bp_shareofcustomer, f.c_bp_shelflifeminpct AS c_bp_shelflifeminpct, f.c_bp_so_creditlimit AS c_bp_so_creditlimit, f.c_bp_socreditstatus AS c_bp_socreditstatus, f.c_bp_so_creditused AS c_bp_so_creditused, f.c_bp_so_description AS c_bp_so_description, f.taxid AS TaxID, f.c_bp_totalopenbalance AS c_bp_totalopenbalance, f.c_bp_updated AS c_bp_updated, f.c_bp_updatedby AS C_BP_UpdatedBy, f.c_bp_url AS c_bp_url, f.m_product_ad_org_id AS M_Product_AD_Org_ID, f.classification AS Classification, f.m_product_copyfrom AS m_product_copyfrom, f.m_product_created AS m_product_created, f.m_product_createdby AS M_Product_CreatedBy, f.c_revenuerecognition_id AS C_RevenueRecognition_ID, f.c_subscriptiontype_id AS C_SubscriptionType_ID, f.c_taxcategory_id AS C_TaxCategory_ID, f.m_product_c_uom_id AS M_Product_C_UOM_ID, f.m_product_description AS m_product_description, f.descriptionurl AS DescriptionURL, f.discontinued AS Discontinued, f.discontinuedat AS DiscontinuedAt, f.documentnote AS DocumentNote, f.group1 AS Group1, f.group2 AS Group2, f.guaranteedays AS GuaranteeDays, f.guaranteedaysmin AS GuaranteeDaysMin, f.help AS Help, f.imageurl AS ImageURL, f.m_product_isactive AS m_product_isactive, f.isdropship AS IsDropShip, f.isexcludeautodelivery AS IsExcludeAutoDelivery, f.isinvoiceprintdetails AS IsInvoicePrintDetails, f.ispicklistprintdetails AS IsPickListPrintDetails, f.ispurchased AS IsPurchased, f.isselfservice AS IsSelfService, f.issold AS IsSold, f.isstocked AS IsStocked, f.m_product_issummary AS m_product_issummary, f.isverified AS IsVerified, f.iswebstorefeatured AS IsWebStoreFeatured, f.lowlevel AS LowLevel, f.m_product_m_attributeset_id AS M_Product_M_AttributeSet_ID, f.m_product_m_asi_id AS M_Product_M_ASI_ID, f.m_freightcategory_id AS M_FreightCategory_ID, f.m_product_m_locator_id AS M_Product_M_Locator_ID, f.m_product_processing AS m_product_processing, f.producttype AS ProductType, f.r_mailtext_id AS R_MailText_ID, f.m_product_salesrep_id AS M_Product_SalesRep_ID, f.s_expensetype_id AS S_ExpenseType_ID, f.shelfdepth AS ShelfDepth,
f.shelfheight AS ShelfHeight, f.shelfwidth AS ShelfWidth, f.sku AS SKU, f.s_resource_id AS S_Resource_ID, f.unitsperpack AS UnitsPerPack, f.unitsperpallet AS UnitsPerPallet, f.m_product_updated AS m_product_updated, f.m_product_updatedby AS M_Product_UpdatedBy, f.versionno AS VersionNo, f.volume AS Volume, f.weight AS Weight, t.ad_pinstance_id AS AD_PInstance_ID, t.matchcode AS MatchCode, f.c_charge_id AS c_charge_id, f.c_costcenter_id AS c_costcenter_id, f.c_department_id AS c_department_id, f.c_employee_id AS c_employee_id, f.customfieldtext1 AS customfieldtext1, f.customfieldtext2 AS customfieldtext2, f.customfieldtext3 AS customfieldtext3, f.customfieldtext4 AS customfieldtext4, f.m_attributesetinstance_id AS m_attributesetinstance_id, f.m_warehouse_id AS m_warehouse_id FROM rv_fact_acct f
JOIN t_reconciliation t ON f.fact_acct_id = t.fact_acct_id
;

