output.. = target/classes/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/,\
               lib/redisson.jar,\
               lib/netty-common.jar,\
               lib/netty-buffer.jar,\
               lib/netty-codec.jar,\
               lib/netty-handler.jar,\
               lib/netty-resolver.jar,\
               lib/netty-transport.jar,\
               lib/reactor-core.jar,\
               lib/reactive-streams.jar,\
               lib/snakeyaml.jar,\
               lib/jackson-core.jar,\
               lib/jackson-databind.jar,\
               lib/jackson-annotations.jar,\
               lib/caffeine.jar
source.. = src/
