ALTER TABLE AD_Package_Imp_Detail ADD CONSTRAINT ADPackageImp_ADPackageImpDetai FOREIGN KEY (AD_Package_Imp_ID) REFERENCES AD_Package_Imp DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE AD_Package_Imp_Detail ADD CONSTRAINT ADTable_ADPackageImpDetail FOREIGN KEY (AD_Table_ID) REFERENCES AD_Table DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE AD_Password_History ADD CONSTRAINT ADUser_ADPasswordHistory FOREIGN KEY (AD_User_ID) REFERENCES AD_User DEFERRABLE INITIALLY DEFERRED;

SELECT register_migration_script('201610291223_NewFKs.sql') FROM dual
;

