name: SonarQube
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to analyze"
        required: true
        default: "master"
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin' # Alternative distribution options are available.
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:5.0.0.4389:sonar \
          -Dsonar.projectKey=${{ vars.sonarProjectKey }} \
          -Dsonar.organization=${{ vars.sonarOrganization }} \
          -Dsonar.exclusions=**/I_*.java,**/X_*.java \
          -Dsonar.host.url=https://sonarcloud.io \
          -DmaterializeProduct=none \
          -DassembleRepository=none \
          -Dsonar.sourceEncoding=UTF-8 \
          -Dsonar.scanner.javaOpts="-Xmx6g" \
          -Dsonar.issue.ignore.multicriteria=e1,e2 \
          -Dsonar.issue.ignore.multicriteria.e1.ruleKey=java:S3252 \
          -Dsonar.issue.ignore.multicriteria.e1.resourceKey=**/*.java \
          -Dsonar.issue.ignore.multicriteria.e2.ruleKey=java:S117 \
          -Dsonar.issue.ignore.multicriteria.e2.resourceKey=**/*.java
          
